"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, LocateFixed, Navigation, Phone, RefreshCw, Volume2, VolumeX } from "lucide-react";
import { apiFetch } from "@/lib/api";

type Coordinate = { latitude: number; longitude: number };
type Profile = { id: string; status: "offline" | "online" | "busy" | "suspended"; rating: number; completedJobs: number; user: { name: string; email: string; role: string }; locations: Coordinate[] };
type Job = { id: string; status: string; pickupAddress: string; pickupLatitude?: number | null; pickupLongitude?: number | null; dropoffAddress: string; dropoffLatitude?: number | null; dropoffLongitude?: number | null; estimatedFare?: number | null; finalFare?: number | null; order?: { orderNumber: string; customer: { name: string; phoneNumber?: string | null } } | null };
type Step = { distance?: number; duration?: number; name?: string; maneuver?: { type?: string; modifier?: string; location?: [number, number] } };
type Route = { distance?: number; duration?: number; geometry?: { coordinates?: [number, number][] }; legs?: { steps?: Step[] }[] };

declare global { interface Window { maplibregl?: any } }
const ACTIVE = ["requested", "searching_rider", "assigned", "accepted", "pickup_started", "picked_up", "delivering"];
const NEXT: Record<string, string> = { assigned: "accepted", accepted: "pickup_started", pickup_started: "picked_up", picked_up: "delivering", delivering: "delivered" };
const LABEL: Record<string, string> = { assigned: "Go to Pickup", accepted: "Confirm Pickup", pickup_started: "Confirm Pickup", picked_up: "Start Delivery", delivering: "Complete Delivery" };

function distanceMeters(a: Coordinate, b: Coordinate) { const r = 6371000; const p1 = a.latitude * Math.PI / 180; const p2 = b.latitude * Math.PI / 180; const dp = (b.latitude - a.latitude) * Math.PI / 180; const dl = (b.longitude - a.longitude) * Math.PI / 180; const h = Math.sin(dp / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(dl / 2) ** 2; return 2 * r * Math.asin(Math.sqrt(h)); }
function formatDistance(m?: number | null) { if (m == null || !Number.isFinite(m)) return "—"; return m >= 1000 ? `${(m / 1000).toFixed(1)} km` : `${Math.max(10, Math.round(m / 10) * 10)} m`; }
function formatTime(s?: number | null) { if (s == null || !Number.isFinite(s)) return "—"; const m = Math.max(1, Math.round(s / 60)); return m < 60 ? `${m} min` : `${Math.floor(m / 60)} hr ${m % 60} min`; }
function stepText(step?: Step) { if (!step) return "Continue straight"; const type = step.maneuver?.type; const mod = step.maneuver?.modifier?.replace(/-/g, " "); const road = step.name ? ` onto ${step.name}` : ""; if (type === "arrive") return "Arrive at destination"; if (type === "depart") return `Head ${mod ?? "straight"}${road}`; if (type === "roundabout" || type === "rotary") return `Take the roundabout${road}`; if (type === "merge") return `Merge ${mod ?? "ahead"}${road}`; if (type === "fork") return `Keep ${mod ?? "straight"}${road}`; if (type === "turn") return `Turn ${mod ?? "ahead"}${road}`; return `Continue ${mod ?? "straight"}${road}`; }
function glyph(step?: Step) { const type = step?.maneuver?.type; const mod = step?.maneuver?.modifier; if (type === "arrive") return "⌂"; if (type === "roundabout" || type === "rotary") return "↻"; if (mod?.includes("left")) return "↰"; if (mod?.includes("right")) return "↱"; return "↑"; }
function nearestOnRoute(point: Coordinate, coords: [number, number][]) { let best = { distance: Infinity, along: 0 }; let along = 0; const latScale = 111320; const lonScale = Math.cos(point.latitude * Math.PI / 180) * latScale; for (let i = 1; i < coords.length; i++) { const a = coords[i - 1]; const b = coords[i]; const ax = (a[0] - point.longitude) * lonScale; const ay = (a[1] - point.latitude) * latScale; const bx = (b[0] - point.longitude) * lonScale; const by = (b[1] - point.latitude) * latScale; const dx = bx - ax; const dy = by - ay; const denom = dx * dx + dy * dy; const t = denom ? Math.max(0, Math.min(1, -(ax * dx + ay * dy) / denom)) : 0; const q: Coordinate = { latitude: a[1] + (b[1] - a[1]) * t, longitude: a[0] + (b[0] - a[0]) * t }; const d = distanceMeters(point, q); const seg = distanceMeters({ latitude: a[1], longitude: a[0] }, { latitude: b[1], longitude: b[0] }); if (d < best.distance) best = { distance: d, along: along + seg * t }; along += seg; } return best; }
function useMapLibre() { const [ready, setReady] = useState(false); useEffect(() => { if (typeof window === "undefined") return; if (window.maplibregl) { setReady(true); return; } const css = document.createElement("link"); css.rel = "stylesheet"; css.href = "https://unpkg.com/maplibre-gl@5.9.0/dist/maplibre-gl.css"; document.head.appendChild(css); const script = document.createElement("script"); script.src = "https://unpkg.com/maplibre-gl@5.9.0/dist/maplibre-gl.js"; script.async = true; script.onload = () => setReady(true); document.body.appendChild(script); return () => { script.remove(); css.remove(); }; }, []); return ready; }

export function RiderAppV10() {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [jobs, setJobs] = useState<Job[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [location, setLocation] = useState<Coordinate | null>(null);
  const [heading, setHeading] = useState(0);
  const [tab, setTab] = useState<"orders" | "map">("orders");
  const [navigating, setNavigating] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const hydrate = useCallback(async () => { const [p, j] = await Promise.all([apiFetch<Profile>("/rider/me"), apiFetch<Job[]>("/rider/jobs")]); setProfile(p); setJobs(j); const active = j.find(x => x.status === "delivering") ?? j.find(x => ACTIVE.includes(x.status)); setSelectedId(active?.id ?? null); if (j.some(x => x.status === "delivering")) { setTab("map"); setNavigating(true); } }, []);
  useEffect(() => { hydrate().catch(e => setError(e instanceof Error ? e.message : "Unable to load rider data")); }, [hydrate]);
  useEffect(() => { if (!profile || profile.status === "offline" || profile.status === "suspended" || !navigator.geolocation) return; const id = navigator.geolocation.watchPosition(p => { const c = { latitude: p.coords.latitude, longitude: p.coords.longitude }; setLocation(c); if (p.coords.heading != null && p.coords.heading >= 0) setHeading(p.coords.heading); void apiFetch("/rider/location", { method: "POST", body: JSON.stringify({ ...c, heading: p.coords.heading ?? undefined, speed: p.coords.speed ?? undefined, accuracy: p.coords.accuracy ?? undefined }) }).catch(() => undefined); }, e => setError(e.message), { enableHighAccuracy: true, maximumAge: 1500, timeout: 10000 }); return () => navigator.geolocation.clearWatch(id); }, [profile?.status]);
  const activeJobs = useMemo(() => jobs.filter(j => ACTIVE.includes(j.status)), [jobs]);
  const deliveredJobs = useMemo(() => jobs.filter(j => j.status === "delivered"), [jobs]);
  const selectedJob = jobs.find(j => j.id === selectedId) ?? activeJobs[0] ?? null;
  async function toggleOnline() { if (!profile || profile.status === "suspended") return; setBusy(true); try { setProfile(await apiFetch<Profile>("/rider/status", { method: "PATCH", body: JSON.stringify({ status: profile.status === "online" ? "offline" : "online" }) })); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update status"); } finally { setBusy(false); } }
  async function advance(job: Job) { const next = NEXT[job.status]; if (!next) return; setBusy(true); try { await apiFetch(`/rider/jobs/${job.id}/status`, { method: "PATCH", body: JSON.stringify({ status: next }) }); await hydrate(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update delivery"); } finally { setBusy(false); } }

  return <div className="min-h-[100dvh] bg-[#FFF6EC] text-[#241C18] -mx-4 -my-6 lg:-mx-8 lg:-my-8"><div className="mx-auto min-h-[100dvh] w-full max-w-[720px] bg-[#FFF6EC] lg:border-x lg:border-[#F0E4D6]">{error ? <div className="absolute left-3 right-3 top-3 z-[200] rounded-2xl bg-[#FFF0E3] px-4 py-3 text-xs font-bold text-[#8A3E1D]">{error}</div> : null}<main className="min-h-[100dvh] pb-20">{tab === "orders" ? <Orders profile={profile} jobs={activeJobs} delivered={deliveredJobs} busy={busy} onOnline={toggleOnline} onRefresh={hydrate} onNavigate={j => { setSelectedId(j.id); setTab("map"); setNavigating(true); }} onAdvance={advance}/> : selectedJob ? <NavigationScreen job={selectedJob} riderLocation={location ?? profile?.locations?.[0] ?? null} heading={heading} navigating={navigating} onBack={() => { setTab("orders"); setNavigating(false); }} onAdvance={advance} busy={busy}/> : <EmptyMap onBack={() => setTab("orders")}/>}</main><nav className="fixed bottom-0 left-1/2 z-50 flex w-full max-w-[720px] -translate-x-1/2 border-t border-[#F0E4D6] bg-white px-2 pb-2 pt-2"><button onClick={() => { setTab("orders"); setNavigating(false); }} className={`flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black ${tab === "orders" ? "text-[#F4581D]" : "text-[#8A817A]"}`}>🧾<span>Orders</span></button><button onClick={() => { setTab("map"); setNavigating(true); }} className={`flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black ${tab === "map" ? "text-[#F4581D]" : "text-[#8A817A]"}`}>🗺️<span>Map</span></button><button className="flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black text-[#8A817A]">📊<span>Earnings</span></button><button className="flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black text-[#8A817A]">👤<span>Profile</span></button></nav></div></div>;
}

function Orders({ profile, jobs, delivered, busy, onOnline, onRefresh, onNavigate, onAdvance }: { profile: Profile | null; jobs: Job[]; delivered: Job[]; busy: boolean; onOnline: () => void; onRefresh: () => void; onNavigate: (job: Job) => void; onAdvance: (job: Job) => void }) { return <div className="pt-5"><div className="mx-5 flex items-center justify-between rounded-full bg-white px-4 py-3 shadow-sm ring-1 ring-[#F0E4D6]"><button disabled={busy} onClick={onOnline} className={`rounded-full px-3 py-1.5 text-xs font-black ${profile?.status === "online" ? "bg-[#E4F6EB] text-[#1FA35A]" : "bg-[#F6EEE7] text-[#8A817A]"}`}>{profile?.status === "online" ? "● Online" : "○ Offline"}</button><span className="text-[11px] font-bold text-[#8A817A]">{jobs.length} active · {(profile?.rating ?? 5).toFixed(1)} ⭐</span></div><div className="mt-6 mb-3 flex items-center justify-between px-5"><div className="text-[15px] font-black">Active Orders</div><div className="rounded-full bg-[#FFE3D2] px-2.5 py-1 text-[10px] font-black text-[#D9430F]">{jobs.length}</div></div>{jobs.length ? jobs.map(job => <OrderCard key={job.id} job={job} busy={busy} onNavigate={onNavigate} onAdvance={onAdvance}/>) : <div className="mx-5 rounded-[22px] bg-white p-7 text-center ring-1 ring-[#F0E4D6]"><div className="text-3xl">🥟</div><div className="mt-2 text-sm font-black">{profile?.status === "online" ? "Waiting for an order" : "You're offline"}</div></div>}<div className="mt-6 mb-3 px-5 text-[15px] font-black">Recent Orders</div><div className="mx-5 rounded-[22px] bg-white ring-1 ring-[#F0E4D6]">{delivered.length ? delivered.slice(0, 8).map((job, i) => <div key={job.id} className={`flex items-center gap-3 px-4 py-3.5 ${i < delivered.length - 1 ? "border-b border-[#F0E4D6]" : ""}`}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#FFE3D2] text-xl">🥟</div><div className="min-w-0 flex-1"><div className="truncate text-[13px] font-black">{job.order?.customer.name ?? "Customer"}</div><div className="truncate text-[11px] text-[#8A817A]">{job.dropoffAddress}</div></div><div className="text-right"><div className="text-xs font-black text-[#1FA35A]">₱{Number(job.finalFare ?? job.estimatedFare ?? 0).toFixed(0)}</div><div className="text-[10px] text-[#8A817A]">Delivered</div></div></div>) : <div className="p-5 text-center text-xs text-[#8A817A]">No deliveries completed yet.</div>}</div><button onClick={onRefresh} className="mx-5 mt-3 flex w-[calc(100%-40px)] items-center justify-center gap-2 rounded-2xl bg-white py-3 text-xs font-black ring-1 ring-[#F0E4D6]"><RefreshCw size={14}/>Refresh</button></div>; }
function OrderCard({ job, busy, onNavigate, onAdvance }: { job: Job; busy: boolean; onNavigate: (job: Job) => void; onAdvance: (job: Job) => void }) { const dropoff = job.status === "picked_up" || job.status === "delivering"; return <div className="mx-5 mb-3 rounded-[22px] border-[1.5px] border-[#F4581D] bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="rounded-[10px] bg-[#FFE3D2] px-2.5 py-1.5 text-[11px] font-extrabold text-[#D9430F]">{job.status === "delivering" ? "🧭 Navigating" : job.status === "assigned" ? "🕐 New Order" : "🚴 Current Order"}</span><span className="text-xs font-extrabold text-[#8A817A]">#{job.order?.orderNumber ?? job.id.slice(-6).toUpperCase()}</span></div><div className="mt-4 flex items-start gap-3.5"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#FFE3D2] text-[26px]">🥟</div><div className="min-w-0 flex-1"><div className="text-[15px] font-extrabold">👤 {job.order?.customer.name ?? "Customer"}</div><div className="mt-1 text-[13px] leading-[18px] text-[#5C5450]">📍 {dropoff ? job.dropoffAddress : job.pickupAddress}</div></div></div><div className="mt-4 flex gap-2"><div className="flex-1 text-[19px] font-black">₱{Number(job.finalFare ?? job.estimatedFare ?? 0).toFixed(0)}</div><button disabled={busy} onClick={() => onNavigate(job)} className="rounded-2xl border border-[#F4581D] bg-white px-3 py-3 text-[12px] font-black text-[#F4581D]"><Navigation size={14} className="mr-1 inline"/>Navigate</button><button disabled={busy || !NEXT[job.status]} onClick={() => onAdvance(job)} className="rounded-2xl bg-[#F4581D] px-3 py-3 text-[12px] font-black text-white">{busy ? "Updating…" : LABEL[job.status] ?? "Open Order"}</button></div>{job.order?.customer.phoneNumber ? <a href={`tel:${job.order.customer.phoneNumber}`} className="mt-2 flex items-center justify-center gap-2 rounded-xl bg-[#F6EEE7] py-2 text-xs font-black text-[#5C5450]"><Phone size={13}/>Call customer</a> : null}</div>; }
function EmptyMap({ onBack }: { onBack: () => void }) { return <div className="flex min-h-[70dvh] items-center justify-center p-6"><div className="text-center"><div className="text-4xl">🗺️</div><div className="mt-2 font-black">No active delivery</div><button onClick={onBack} className="mt-4 rounded-2xl bg-[#F4581D] px-5 py-3 text-xs font-black text-white">Back to orders</button></div></div>; }

function NavigationScreen({ job, riderLocation, heading, navigating, onBack, onAdvance, busy }: { job: Job; riderLocation: Coordinate | null; heading: number; navigating: boolean; onBack: () => void; onAdvance: (job: Job) => void; busy: boolean }) {
  const mapReady = useMapLibre(); const nodeRef = useRef<HTMLDivElement | null>(null); const mapRef = useRef<any>(null); const markerRef = useRef<any>(null); const routeRef = useRef<Route | null>(null); const coordsRef = useRef<[number, number][]>([]); const lastRouteRef = useRef(0); const requestRef = useRef(0); const [route, setRoute] = useState<Route | null>(null); const [loading, setLoading] = useState(false); const [routeError, setRouteError] = useState<string | null>(null); const [follow, setFollow] = useState(true); const [voice, setVoice] = useState(false); const [progress, setProgress] = useState(0); const [offRoute, setOffRoute] = useState(false); const [started, setStarted] = useState(false); const userGestureRef = useRef(false);
  const destination = useMemo<Coordinate | null>(() => { const drop = job.status === "picked_up" || job.status === "delivering"; const lat = drop ? job.dropoffLatitude : job.pickupLatitude; const lng = drop ? job.dropoffLongitude : job.pickupLongitude; return lat != null && lng != null ? { latitude: Number(lat), longitude: Number(lng) } : null; }, [job]);
  const steps = useMemo(() => (route?.legs ?? []).flatMap(l => l.steps ?? []), [route]);
  const offsets = useMemo(() => { let n = 0; return steps.map(step => { const x = { step, start: n }; n += step.distance ?? 0; return x; }); }, [steps]);
  const current = useMemo(() => { if (!offsets.length) return undefined; return offsets.find(x => x.start + (x.step.distance ?? 0) > progress + 8)?.step ?? offsets[offsets.length - 1]?.step; }, [offsets, progress]);
  const currentDistance = useMemo(() => { const item = offsets.find(x => x.step === current); return item && current ? Math.max(0, item.start + (current.distance ?? 0) - progress) : null; }, [offsets, current, progress]);
  const totalDistance = route?.distance ?? 0; const totalDuration = route?.duration ?? 0; const remainingDistance = Math.max(0, totalDistance - progress); const etaSeconds = Math.max(0, totalDuration - (progress / Math.max(totalDistance, 1)) * totalDuration);

  const fetchRoute = useCallback(async (force = false) => { if (!riderLocation || !destination) return; const t = Date.now(); if (!force && t - lastRouteRef.current < 4500) return; lastRouteRef.current = t; const id = ++requestRef.current; setLoading(true); setRouteError(null); try { const q = new URLSearchParams({ originLat: String(riderLocation.latitude), originLng: String(riderLocation.longitude), destLat: String(destination.latitude), destLng: String(destination.longitude) }); const res = await fetch(`/api/rider/route?${q}`, { cache: "no-store" }); const data = await res.json(); if (!res.ok) throw new Error(data?.error ?? "Unable to calculate route"); const next = data?.routes?.[0] as Route | undefined; if (!next?.geometry?.coordinates?.length) throw new Error("No drivable route found"); if (id !== requestRef.current) return; routeRef.current = next; coordsRef.current = next.geometry.coordinates; setRoute(next); setStarted(true); } catch (e) { if (id === requestRef.current) setRouteError(e instanceof Error ? e.message : "Unable to calculate route"); } finally { if (id === requestRef.current) setLoading(false); } }, [destination, riderLocation]);

  useEffect(() => { if (!mapReady || !nodeRef.current || mapRef.current) return; const ml = window.maplibregl; const c = riderLocation ?? destination ?? { latitude: 14.5995, longitude: 120.9842 }; const map = new ml.Map({ container: nodeRef.current, style: "https://tiles.openfreemap.org/styles/liberty", center: [c.longitude, c.latitude], zoom: 16.5, attributionControl: true }); mapRef.current = map; map.addControl(new ml.NavigationControl({ showCompass: false }), "bottom-right"); map.on("load", () => { map.addSource("rider-route", { type: "geojson", data: { type: "Feature", properties: {}, geometry: { type: "LineString", coordinates: [] } } }); map.addLayer({ id: "rider-route-casing", type: "line", source: "rider-route", paint: { "line-color": "#ffffff", "line-width": 11, "line-opacity": 0.96 } }); map.addLayer({ id: "rider-route-line", type: "line", source: "rider-route", paint: { "line-color": "#4285F4", "line-width": 6, "line-opacity": 1 } }); }); map.on("dragstart", () => { userGestureRef.current = true; setFollow(false); }); map.on("zoomstart", () => { userGestureRef.current = true; setFollow(false); }); return () => { markerRef.current?.remove(); map.remove(); mapRef.current = null; }; }, [mapReady]);
  useEffect(() => { const map = mapRef.current; if (!map || !route?.geometry?.coordinates?.length) return; const apply = () => { const source = map.getSource("rider-route"); source?.setData({ type: "Feature", properties: {}, geometry: { type: "LineString", coordinates: route.geometry!.coordinates! } }); }; if (map.isStyleLoaded()) apply(); else map.once("load", apply); }, [route]);
  useEffect(() => { const map = mapRef.current; const ml = window.maplibregl; if (!map || !ml || !riderLocation) return; const pos: [number, number] = [riderLocation.longitude, riderLocation.latitude]; if (!markerRef.current) { const el = document.createElement("div"); el.className = "flex h-12 w-12 items-center justify-center"; el.innerHTML = `<div style="width:0;height:0;border-left:9px solid transparent;border-right:9px solid transparent;border-bottom:20px solid #4285F4;transform:rotate(${heading}deg);filter:drop-shadow(0 2px 3px rgba(0,0,0,.35))"></div><div style="position:absolute;width:14px;height:14px;border-radius:50%;background:#fff;box-shadow:0 1px 4px rgba(0,0,0,.35)"></div>`; markerRef.current = new ml.Marker({ element: el, anchor: "center" }).setLngLat(pos).addTo(map); } else { markerRef.current.setLngLat(pos); const arrow = markerRef.current.getElement()?.firstElementChild as HTMLElement | null; if (arrow) arrow.style.transform = `rotate(${heading}deg)`; } if (follow && navigating && !userGestureRef.current) map.easeTo({ center: pos, zoom: 17.4, bearing: heading, pitch: 48, duration: 550, essential: true }); }, [riderLocation, heading, follow, navigating]);
  useEffect(() => { if (!riderLocation || !coordsRef.current.length) return; const nearest = nearestOnRoute(riderLocation, coordsRef.current); setProgress(nearest.along); const off = nearest.distance > 60 && (!destination || distanceMeters(riderLocation, destination) > 40); setOffRoute(off); if (off) void fetchRoute(true); }, [riderLocation, destination, fetchRoute]);
  useEffect(() => { if (!riderLocation || !destination) return; void fetchRoute(!route); const timer = window.setInterval(() => { if (routeRef.current) void fetchRoute(false); }, 5000); return () => window.clearInterval(timer); }, [riderLocation, destination, fetchRoute, route]);
  useEffect(() => { if (!voice || !current || (currentDistance ?? 9999) > 120 || typeof window === "undefined" || !("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(stepText(current))); }, [voice, current, currentDistance]);
  const recenter = () => { userGestureRef.current = false; setFollow(true); if (mapRef.current && riderLocation) mapRef.current.easeTo({ center: [riderLocation.longitude, riderLocation.latitude], zoom: 17.4, bearing: heading, pitch: 48, duration: 450, essential: true }); };
  const status = offRoute ? "Recalculating route…" : routeError ? "Route unavailable" : loading && !route ? "Calculating route…" : started ? "On route" : "Ready";
  const destinationLabel = job.status === "picked_up" || job.status === "delivering" ? job.dropoffAddress : job.pickupAddress;

  return <div className="relative h-[calc(100dvh-80px)] min-h-[680px] overflow-hidden bg-[#E9E6DF]">
    <div ref={nodeRef} className="absolute inset-0" />
    <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-black/30 via-transparent to-black/20" />
    <div className="absolute left-3 right-3 top-3 z-30 flex gap-2"><button onClick={onBack} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-white shadow-xl"><ArrowLeft size={19}/></button><div className="min-w-0 flex-1 rounded-[20px] bg-[#111827] text-white shadow-xl"><div className="flex items-center gap-3 px-4 py-3"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white text-3xl font-black text-[#111827]">{glyph(current)}</div><div className="min-w-0 flex-1"><div className="text-[22px] font-black leading-6">{currentDistance != null ? formatDistance(currentDistance) : "—"}</div><div className="truncate text-[13px] font-semibold text-white/75">{stepText(current)}</div></div><button onClick={() => setVoice(v => !v)} className="rounded-full p-2">{voice ? <Volume2 size={19}/> : <VolumeX size={19}/>}</button></div></div></div>
    <div className="absolute right-3 top-[78px] z-30 flex flex-col gap-2"><button onClick={recenter} className={`flex h-11 w-11 items-center justify-center rounded-full bg-white shadow-xl ${follow ? "text-[#4285F4]" : "text-[#555]"}`}><LocateFixed size={19}/></button><button onClick={() => void fetchRoute(true)} className="flex h-11 w-11 items-center justify-center rounded-full bg-white shadow-xl"><RefreshCw size={17} className={loading ? "animate-spin" : ""}/></button></div>
    {offRoute || routeError ? <div className="absolute left-1/2 top-[128px] z-30 -translate-x-1/2 rounded-full bg-[#111827] px-4 py-2 text-[11px] font-black text-white shadow-xl">{status}</div> : null}
    <div className="absolute bottom-0 left-0 right-0 z-30 rounded-t-[28px] bg-white px-4 pb-5 pt-3 shadow-[0_-8px_30px_rgba(0,0,0,.16)]"><div className="mx-auto mb-3 h-1.5 w-10 rounded-full bg-[#D8D2CA]"/><div className="flex items-end justify-between gap-4"><div><div className="text-[30px] font-black leading-8">{formatTime(etaSeconds || totalDuration)}</div><div className="mt-1 text-xs font-bold text-[#756D66]">{formatDistance(remainingDistance || distanceMeters(riderLocation ?? destination ?? { latitude: 0, longitude: 0 }, destination ?? riderLocation ?? { latitude: 0, longitude: 0 }))} · {status}</div></div><div className="text-right"><div className="text-xs font-bold uppercase tracking-[.12em] text-[#8A817A]">Arrive</div><div className="text-[17px] font-black">{new Date(Date.now() + (etaSeconds || totalDuration) * 1000).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</div></div></div><div className="mt-3 rounded-2xl bg-[#F5F7FA] px-3 py-2.5"><div className="flex items-center gap-2 text-xs font-bold"><Navigation size={14} className="text-[#4285F4]"/><span className="truncate">{destinationLabel}</span></div><div className="mt-1 text-[11px] text-[#8A817A]">{steps.length ? `${steps.length} turns · GPS route following` : "Road route"}</div></div><div className="mt-3 flex gap-2"><button onClick={() => { setFollow(true); setNavigatingLocal(true); recenter(); }} className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-[#4285F4] py-3.5 text-sm font-black text-white"><Navigation size={16}/> {navigating ? "Following route" : "Start navigation"}</button><button disabled={busy || !NEXT[job.status]} onClick={() => onAdvance(job)} className="rounded-2xl bg-[#F4581D] px-4 py-3.5 text-xs font-black text-white">{busy ? "Updating…" : LABEL[job.status] ?? "Complete"}</button></div>{job.order?.customer.phoneNumber ? <a href={`tel:${job.order.customer.phoneNumber}`} className="mt-2 flex items-center justify-center gap-2 rounded-xl bg-[#F6EEE7] py-2.5 text-xs font-black text-[#5C5450]"><Phone size={13}/>Call customer</a> : null}<div className="mt-2 text-center text-[10px] font-semibold text-[#938A82]">Live GPS · automatic camera · turn progression · off-route rerouting</div></div>
  </div>;
}
