"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Bell, LocateFixed, MapPin, Navigation, Phone, RefreshCw, ArrowLeft, Volume2 } from "lucide-react";
import { apiFetch } from "@/lib/api";

type Coordinate = { latitude: number; longitude: number };
type Profile = { id: string; status: "offline" | "online" | "busy" | "suspended"; rating: number; completedJobs: number; user: { name: string; email: string; role: string }; locations: Coordinate[] };
type Job = { id: string; status: string; pickupAddress: string; pickupLatitude?: number | null; pickupLongitude?: number | null; dropoffAddress: string; dropoffLatitude?: number | null; dropoffLongitude?: number | null; distanceKm?: number | null; estimatedDurationMinutes?: number | null; estimatedFare?: number | null; finalFare?: number | null; order?: { orderNumber: string; quantity?: number; customer: { name: string; phoneNumber?: string | null } } | null };
type RouteStep = { distance: number; duration: number; name?: string; maneuver?: { type?: string; modifier?: string } };
type RouteData = { distance: number; duration: number; geometry: { coordinates: [number, number][] }; legs?: Array<{ steps?: RouteStep[] }> };

declare global { interface Window { L?: any } }
const ACTIVE = ["requested", "searching_rider", "assigned", "accepted", "pickup_started", "picked_up", "delivering"];
const NEXT: Record<string, string> = { assigned: "accepted", accepted: "pickup_started", pickup_started: "picked_up", picked_up: "delivering", delivering: "delivered" };
const LABEL: Record<string, string> = { assigned: "Go to Pickup", accepted: "Confirm Pickup", pickup_started: "Confirm Pickup", picked_up: "Start Delivery", delivering: "Complete Delivery" };

function valid(c?: Coordinate | null): c is Coordinate { return !!c && Number.isFinite(c.latitude) && Number.isFinite(c.longitude); }
function meters(a: Coordinate, b: Coordinate) { const r=6371000, p1=a.latitude*Math.PI/180, p2=b.latitude*Math.PI/180, dp=(b.latitude-a.latitude)*Math.PI/180, dl=(b.longitude-a.longitude)*Math.PI/180; const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2; return 2*r*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)); }
function headingText(type?: string, modifier?: string) { if (type === "arrive") return "Arrive at your destination"; if (type === "depart") return "Head out"; if (type === "roundabout") return "Enter the roundabout"; if (type === "merge") return `Merge${modifier ? ` ${modifier}` : ""}`; if (type === "fork") return `Keep ${modifier ?? "ahead"}`; if (type === "continue") return "Continue straight"; if (modifier) return `Turn ${modifier}`; return "Continue"; }
function useLeaflet() { const [ready,setReady]=useState(false); useEffect(()=>{ if(typeof window==='undefined') return; if(window.L){setReady(true);return;} const css=document.createElement('link'); css.rel='stylesheet'; css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css'; css.dataset.riderLeaflet='true'; document.head.appendChild(css); const s=document.createElement('script'); s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js'; s.async=true; s.onload=()=>setReady(true); document.body.appendChild(s); return()=>{s.remove();css.remove();}; },[]); return ready; }

export function RiderAppV3(){
 const [profile,setProfile]=useState<Profile|null>(null),[jobs,setJobs]=useState<Job[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[location,setLocation]=useState<Coordinate|null>(null),[heading,setHeading]=useState(0),[tab,setTab]=useState<'orders'|'map'>('orders'),[navigating,setNavigating]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const hydrate=useCallback(async()=>{const [p,j]=await Promise.all([apiFetch<Profile>('/rider/me'),apiFetch<Job[]>('/rider/jobs')]);setProfile(p);setJobs(j);setSelectedId(old=>old&&j.some(x=>x.id===old)?old:j.find(x=>ACTIVE.includes(x.status))?.id??null);},[]);
 useEffect(()=>{hydrate().catch(e=>setError(e instanceof Error?e.message:'Unable to load rider account'));},[hydrate]);
 useEffect(()=>{if(!profile||profile.status==='offline'||profile.status==='suspended'||!navigator.geolocation)return;const id=navigator.geolocation.watchPosition(pos=>{const c={latitude:pos.coords.latitude,longitude:pos.coords.longitude};setLocation(c);if(pos.coords.heading!=null&&pos.coords.heading>=0)setHeading(pos.coords.heading);void apiFetch('/rider/location',{method:'POST',body:JSON.stringify({...c,heading:pos.coords.heading??undefined,speed:pos.coords.speed??undefined,accuracy:pos.coords.accuracy??undefined})}).catch(()=>undefined);},()=>undefined,{enableHighAccuracy:true,maximumAge:2000,timeout:10000});return()=>navigator.geolocation.clearWatch(id);},[profile?.status]);
 const active=useMemo(()=>jobs.filter(j=>ACTIVE.includes(j.status)),[jobs]), delivered=useMemo(()=>jobs.filter(j=>j.status==='delivered'),[jobs]), selected=jobs.find(j=>j.id===selectedId)??active[0]??null;
 async function toggle(){if(!profile||profile.status==='suspended')return;setBusy(true);try{setProfile(await apiFetch<Profile>('/rider/status',{method:'PATCH',body:JSON.stringify({status:profile.status==='online'?'offline':'online'})}));}catch(e){setError(e instanceof Error?e.message:'Unable to update status');}finally{setBusy(false);}}
 async function advance(job:Job){if(!NEXT[job.status])return;setBusy(true);try{await apiFetch(`/rider/jobs/${job.id}/status`,{method:'PATCH',body:JSON.stringify({status:NEXT[job.status]})});await hydrate();}catch(e){setError(e instanceof Error?e.message:'Unable to update order');}finally{setBusy(false);}}
 function openNav(job:Job){setSelectedId(job.id);setTab('map');setNavigating(true);}
 return <div className='min-h-[100dvh] bg-[#FFF6EC] text-[#241C18] -mx-4 -my-6 lg:-mx-8 lg:-my-8'><div className='mx-auto flex min-h-[100dvh] w-full max-w-[680px] flex-col bg-[#FFF6EC] shadow-sm lg:border-x lg:border-[#F0E4D6]'><header className='rounded-b-[30px] bg-[#F4581D] px-5 pb-5 pt-5 text-white'><div className='flex items-center justify-between'><button className='flex h-10 w-10 items-center justify-center'><ArrowLeft size={22}/></button><div className='text-center'><div className='text-[15px] font-extrabold italic'>Empanada</div><div className='text-[17px] font-black italic text-[#3B140A]'>Hauz Rider</div></div><Bell size={21}/></div></header>{error&&<div className='mx-5 mt-3 rounded-2xl border border-[#F3D2B6] bg-[#FFF0E3] px-4 py-3 text-xs font-semibold text-[#8A3E1D]'>{error}</div>}<main className='flex-1 overflow-y-auto pb-24'>{tab==='orders'?<Orders profile={profile} jobs={active} delivered={delivered} busy={busy} onOnline={toggle} onRefresh={hydrate} onNavigate={openNav} onAdvance={advance}/>:<NavigationScreen job={selected} riderLocation={location??profile?.locations?.[0]??null} heading={heading} navigating={navigating} onBack={()=>{setNavigating(false);setTab('orders')}} onAdvance={advance} busy={busy}/>}</main><nav className='fixed bottom-0 left-1/2 z-50 flex w-full max-w-[680px] -translate-x-1/2 border-t border-[#F0E4D6] bg-white px-2 pb-2 pt-2 lg:absolute'><button onClick={()=>setTab('orders')} className={`flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black ${tab==='orders'?'text-[#F4581D]':'text-[#8A817A]'}`}>🧾<span>Orders</span></button><button onClick={()=>setTab('map')} className={`flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black ${tab==='map'?'text-[#F4581D]':'text-[#8A817A]'}`}>🗺️<span>Map</span></button><button className='flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black text-[#8A817A]'>📊<span>Earnings</span></button><button className='flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black text-[#8A817A]'>👤<span>Profile</span></button></nav></div></div>;
}

function Orders({profile,jobs,delivered,busy,onOnline,onRefresh,onNavigate,onAdvance}:{profile:Profile|null;jobs:Job[];delivered:Job[];busy:boolean;onOnline:()=>void;onRefresh:()=>void;onNavigate:(j:Job)=>void;onAdvance:(j:Job)=>void}){return <div className='pt-5'><div className='mx-5 rounded-full bg-white px-4 py-3 shadow-sm ring-1 ring-[#F0E4D6]'><div className='flex items-center justify-between'><button disabled={busy} onClick={onOnline} className={`rounded-full px-3 py-1.5 text-xs font-black ${profile?.status==='online'?'bg-[#E4F6EB] text-[#1FA35A]':'bg-[#F6EEE7] text-[#8A817A]'}`}>{profile?.status==='online'?'● Online':'○ Offline'}</button><span className='text-[11px] font-bold text-[#8A817A]'>{jobs.length} active · {(profile?.rating??5).toFixed(1)} ⭐</span></div></div><div className='mt-3 flex gap-3 px-5'><Stat value={String(jobs.length)} label='Active Orders'/><Stat value={String(profile?.completedJobs??0)} label='Completed'/><Stat value={`${(profile?.rating??5).toFixed(1)} ⭐`} label='Rider Rating'/></div><Title text='Active Orders' count={jobs.length}/>{jobs.length?jobs.map(j=><OrderCard key={j.id} job={j} busy={busy} onNavigate={onNavigate} onAdvance={onAdvance}/>):<div className='mx-5 rounded-[22px] bg-white p-7 text-center shadow-sm ring-1 ring-[#F0E4D6]'><div className='text-3xl'>🥟</div><div className='mt-2 text-sm font-black'>{profile?.status==='online'?'Waiting for an order':"You're offline"}</div><div className='mt-1 text-xs text-[#8A817A]'>{profile?.status==='online'?'Dispatch will notify you when a delivery is assigned.':'Go online when you’re ready to receive deliveries.'}</div></div>}<Title text='Recent Orders'/><div className='mx-5 rounded-[22px] bg-white shadow-sm ring-1 ring-[#F0E4D6]'>{delivered.length?delivered.slice(0,8).map((j,i)=><div key={j.id} className={`flex items-center gap-3 px-4 py-3.5 ${i===Math.min(7,delivered.length-1)?'':'border-b border-[#F0E4D6]'}`}><div className='flex h-11 w-11 items-center justify-center rounded-xl bg-[#FFE3D2] text-xl'>🥟</div><div className='min-w-0 flex-1'><div className='truncate text-[13px] font-black'>{j.order?.customer.name??'Customer'}</div><div className='truncate text-[11px] text-[#8A817A]'>{j.dropoffAddress}</div></div><div className='text-right'><div className='text-xs font-black text-[#1FA35A]'>₱{Number(j.finalFare??j.estimatedFare??0).toFixed(0)}</div><div className='text-[10px] text-[#8A817A]'>Delivered</div></div></div>):<div className='p-5 text-center text-xs text-[#8A817A]'>No deliveries completed yet.</div>}</div><button onClick={onRefresh} className='mx-5 mt-3 flex w-[calc(100%-40px)] items-center justify-center gap-2 rounded-2xl bg-white py-3 text-xs font-black text-[#5C5450] ring-1 ring-[#F0E4D6]'><RefreshCw size={14}/> Refresh</button></div>}
function OrderCard({job,busy,onNavigate,onAdvance}:{job:Job;busy:boolean;onNavigate:(j:Job)=>void;onAdvance:(j:Job)=>void}){const toDrop=['picked_up','delivering'].includes(job.status);const fare=Number(job.finalFare??job.estimatedFare??0);return <div className='mx-5 mb-3 rounded-[22px] border-[1.5px] border-[#F4581D] bg-white p-4 shadow-sm'><div className='flex items-center justify-between'><span className='rounded-[10px] bg-[#FFE3D2] px-2.5 py-1.5 text-[11px] font-extrabold text-[#D9430F]'>{job.status==='assigned'?'🕐 New Order':'🚴 Current Order'}</span><span className='text-xs font-extrabold text-[#8A817A]'>#{job.order?.orderNumber??job.id.slice(-6).toUpperCase()}</span></div><div className='mt-4 flex items-start gap-3.5'><div className='flex h-14 w-14 items-center justify-center rounded-2xl bg-[#FFE3D2] text-[26px]'>🥟</div><div className='min-w-0 flex-1'><div className='text-[15px] font-extrabold'>👤 {job.order?.customer.name??'Customer'}</div><div className='mt-1 text-[13px] leading-[18px] text-[#5C5450]'>📍 {toDrop?job.dropoffAddress:job.pickupAddress}</div></div></div><div className='mt-4 flex gap-2'><div className='flex-1'><div className='text-[19px] font-black'>₱{fare.toFixed(0)}</div>{job.order?.quantity&&<div className='text-[11px] text-[#8A817A]'>{job.order.quantity} pcs Empanada</div>}</div><button disabled={busy} onClick={()=>onNavigate(job)} className='rounded-2xl border border-[#F4581D] bg-white px-3 py-3 text-[12px] font-black text-[#F4581D]'><Navigation size={14} className='mr-1 inline'/>Navigate</button><button disabled={busy||!NEXT[job.status]} onClick={()=>onAdvance(job)} className='rounded-2xl bg-[#F4581D] px-3 py-3 text-[12px] font-black text-white'>{busy?'Updating…':LABEL[job.status]??'Open Order'}</button></div>{job.order?.customer.phoneNumber&&<a href={`tel:${job.order.customer.phoneNumber}`} className='mt-2 flex items-center justify-center gap-2 rounded-xl bg-[#F6EEE7] py-2 text-xs font-black text-[#5C5450]'><Phone size={13}/>Call customer</a>}</div>}
function Title({text,count}:{text:string;count?:number}){return <div className='mt-6 mb-3 flex items-center justify-between px-5'><div className='text-[15px] font-black'>{text}</div>{count!==undefined&&<div className='rounded-full bg-[#FFE3D2] px-2.5 py-1 text-[10px] font-black text-[#D9430F]'>{count}</div>}</div>}
function Stat({value,label}:{value:string;label:string}){return <div className='flex-1 rounded-[18px] bg-white p-3 text-center shadow-sm ring-1 ring-[#F0E4D6]'><div className='text-[17px] font-black'>{value}</div><div className='mt-0.5 text-[10px] text-[#8A817A]'>{label}</div></div>}

function NavigationScreen({job,riderLocation,heading,navigating,onBack,onAdvance,busy}:{job:Job|null;riderLocation:Coordinate|null;heading:number;navigating:boolean;onBack:()=>void;onAdvance:(j:Job)=>void;busy:boolean}){const leaflet=useLeaflet();const mapEl=useRef<HTMLDivElement|null>(null),mapRef=useRef<any>(null),routeLayer=useRef<any>(null),riderMarker=useRef<any>(null),lastRouteOrigin=useRef<Coordinate|null>(null),lastDestination=useRef<string>('');const [route,setRoute]=useState<RouteData|null>(null),[routeError,setRouteError]=useState<string|null>(null),[follow,setFollow]=useState(true);const [stepIndex,setStepIndex]=useState(0);
 const destination=useMemo(()=>{if(!job)return null;const drop=['picked_up','delivering'].includes(job.status);const c=drop?{latitude:Number(job.dropoffLatitude),longitude:Number(job.dropoffLongitude)}:{latitude:Number(job.pickupLatitude),longitude:Number(job.pickupLongitude)};return valid(c)?c:null;},[job]);
 useEffect(()=>{if(!leaflet||!mapEl.current||mapRef.current)return;const L=window.L;const map=L.map(mapEl.current,{zoomControl:false,attributionControl:true}).setView([10.3157,123.8854],14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);mapRef.current=map;setTimeout(()=>map.invalidateSize(),150);return()=>{map.remove();mapRef.current=null;};},[leaflet]);
 useEffect(()=>{if(!mapRef.current||!window.L||!riderLocation)return;const L=window.L;if(!riderMarker.current){riderMarker.current=L.marker([riderLocation.latitude,riderLocation.longitude],{icon:L.divIcon({className:'rider-arrow',html:'<div style="width:44px;height:44px;border-radius:50%;background:#F4581D;border:4px solid white;box-shadow:0 5px 18px rgba(0,0,0,.25);display:flex;align-items:center;justify-content:center;color:white;font-size:20px">➤</div>',iconSize:[44,44],iconAnchor:[22,22]})}).addTo(mapRef.current);}riderMarker.current.setLatLng([riderLocation.latitude,riderLocation.longitude]);const el=riderMarker.current.getElement()?.querySelector('div');if(el)el.style.transform=`rotate(${heading}deg)`;if(follow)mapRef.current.setView([riderLocation.latitude,riderLocation.longitude],17,{animate:true});},[riderLocation,heading,follow]);
 useEffect(()=>{if(!mapRef.current||!window.L||!destination)return;const L=window.L;const key=`${destination.latitude.toFixed(5)},${destination.longitude.toFixed(5)}`;const shouldFetch=!lastRouteOrigin.current||!lastDestination.current||lastDestination.current!==key||(riderLocation&&meters(lastRouteOrigin.current,riderLocation)>100);if(!shouldFetch)return;lastRouteOrigin.current=riderLocation??lastRouteOrigin.current;lastDestination.current=key;setRouteError(null);const origin=riderLocation??destination; if(!riderLocation){setRoute(null);return;}const url=`https://router.project-osrm.org/route/v1/driving/${origin.longitude},${origin.latitude};${destination.longitude},${destination.latitude}?overview=full&geometries=geojson&steps=true`;fetch(url).then(r=>r.ok?r.json():Promise.reject(new Error('Routing service unavailable'))).then((data:RouteData&{code:string})=>{if(data.code!=='Ok')throw new Error('No drivable route found');setRoute(data);setStepIndex(0);}).catch(e=>setRouteError(e instanceof Error?e.message:'Unable to calculate route'));},[destination,riderLocation]);
 useEffect(()=>{if(!mapRef.current||!window.L||!route)return;const L=window.L;if(routeLayer.current)routeLayer.current.remove();const latlngs=route.geometry.coordinates.map(([lon,lat])=>[lat,lon]);routeLayer.current=L.polyline(latlngs,{color:'#F4581D',weight:7,opacity:.95}).addTo(mapRef.current);if(follow)mapRef.current.fitBounds(routeLayer.current.getBounds(),{padding:[50,110],maxZoom:17});},[route,follow]);
 const steps=useMemo(()=>route?.legs?.flatMap(l=>l.steps??[])??[],[route]);const step=steps[Math.min(stepIndex,Math.max(steps.length-1,0))];const eta=route?Math.max(1,Math.round(route.duration/60)):null;const km=route?route.distance/1000:null;
 useEffect(()=>{if(!steps.length||!riderLocation)return;let best=stepIndex,bestDist=Infinity;for(let i=stepIndex;i<Math.min(steps.length,stepIndex+3);i++){const s=steps[i];const d=Math.abs((s.distance??0));if(d<bestDist){bestDist=d;}}if(bestDist<35&&stepIndex<steps.length-1)setStepIndex(i=>i+1);},[riderLocation,steps,stepIndex]);
 if(!job)return <div className='p-8 text-center text-sm text-[#8A817A]'>No active delivery selected.</div>;
 const drop=['picked_up','delivering'].includes(job.status);return <div className='relative h-[calc(100dvh-130px)] min-h-[650px] bg-slate-200'><div ref={mapEl} className='absolute inset-0'/><div className='absolute left-4 right-4 top-4 z-[500] flex items-center justify-between'><button onClick={onBack} className='flex h-11 w-11 items-center justify-center rounded-2xl bg-white shadow-xl'><ArrowLeft size={20}/></button><div className='rounded-2xl bg-white px-4 py-2 shadow-xl'><div className='text-[10px] font-black uppercase tracking-widest text-[#8A817A]'>{drop?'Drop-off':'Pickup'}</div><div className='max-w-[210px] truncate text-xs font-black'>{drop?job.order?.customer.name??'Customer':'Empanada Hauz'}</div></div><button onClick={()=>{setFollow(true);if(riderLocation&&mapRef.current)mapRef.current.setView([riderLocation.latitude,riderLocation.longitude],17,{animate:true});}} className='flex h-11 w-11 items-center justify-center rounded-2xl bg-white shadow-xl'><LocateFixed size={19}/></button></div><div className='absolute left-4 right-4 top-[76px] z-[500] rounded-3xl bg-white p-4 shadow-2xl'><div className='flex items-center gap-3'><div className='rounded-2xl bg-[#F4581D] p-3 text-white'><Navigation size={22}/></div><div className='min-w-0 flex-1'><div className='text-2xl font-black leading-none'>{step?headingText(step.maneuver?.type,step.maneuver?.modifier):'Calculating route…'}</div><div className='mt-1 truncate text-xs font-semibold text-[#5C5450]'>{step?.name|| (drop?job.dropoffAddress:job.pickupAddress)}</div></div><button className='flex h-10 w-10 items-center justify-center rounded-full bg-[#FFF1E8] text-[#F4581D]'><Volume2 size={18}/></button></div>{step&&<div className='mt-3 text-[12px] font-bold text-[#8A817A]'>Next maneuver in {Math.max(1,Math.round(step.distance))} m</div>}</div><div className='absolute bottom-4 left-4 right-4 z-[500] rounded-3xl bg-white p-4 shadow-2xl'><div className='flex items-end justify-between'><div><div className='text-3xl font-black'>{eta??'—'} <span className='text-sm'>min</span></div><div className='text-xs font-bold text-[#8A817A]'>{km!=null?`${km.toFixed(1)} km`:'Calculating'} · live rerouting</div></div><div className='text-right'><div className='text-xs font-black'>{drop?job.dropoffAddress:job.pickupAddress}</div><div className='mt-1 text-[11px] text-[#8A817A]'>{location?'GPS active':'Waiting for GPS'}</div></div></div><div className='mt-3 flex gap-2'><button onClick={()=>setFollow(v=>!v)} className='flex-1 rounded-2xl bg-[#F6EEE7] py-3 text-xs font-black text-[#5C5450]'>{follow?'Following rider':'Free map'}</button><button disabled={busy||!NEXT[job.status]} onClick={()=>onAdvance(job)} className='flex-1 rounded-2xl bg-[#F4581D] py-3 text-xs font-black text-white'>{busy?'Updating…':LABEL[job.status]}</button></div>{routeError&&<div className='mt-2 text-[11px] font-semibold text-red-600'>{routeError}</div>}</div></div>;
}
