"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, LocateFixed, Navigation, Phone, RefreshCw, Volume2, VolumeX } from "lucide-react";
import { apiFetch } from "@/lib/api";

type Point = { latitude: number; longitude: number };
type Job = { id: string; status: string; pickupAddress: string; pickupLatitude?: number | null; pickupLongitude?: number | null; dropoffAddress: string; dropoffLatitude?: number | null; dropoffLongitude?: number | null; estimatedFare?: number | null; finalFare?: number | null; deliveryFee?: number | null; codAmount?: number | null; order?: { customer: { name: string; phoneNumber?: string | null }; codAmount?: number | null; amountDue?: number | null; totalAmount?: number | null; deliveryFee?: number | null } | null };
type Step = { distance?: number; duration?: number; name?: string; maneuver?: { type?: string; modifier?: string } };
type Route = { distance: number; duration: number; geometry?: { coordinates?: [number, number][] }; legs?: { steps?: Step[] }[] };
type RouteResponse = { routes?: Route[]; distanceMeters?: number; duration?: string | number; polyline?: string };
declare global { interface Window { maplibregl?: any } }

const NEXT: Record<string, string> = { assigned: "accepted", accepted: "pickup_started", pickup_started: "picked_up", picked_up: "delivering", delivering: "delivered" };
const ACTION: Record<string, string> = { assigned: "Confirm acceptance", accepted: "Start pickup", pickup_started: "Confirm pickup", picked_up: "Start delivery", delivering: "Complete delivery" };
const MAP_STYLE = "https://tiles.openfreemap.org/styles/liberty";
const MAP_FALLBACK_STYLE = "https://demotiles.maplibre.org/style.json";

function meters(a: Point, b: Point) { const r = 6371000; const p1 = a.latitude * Math.PI / 180; const p2 = b.latitude * Math.PI / 180; const d1 = (b.latitude - a.latitude) * Math.PI / 180; const d2 = (b.longitude - a.longitude) * Math.PI / 180; const h = Math.sin(d1 / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(d2 / 2) ** 2; return 2 * r * Math.asin(Math.sqrt(h)); }
function distanceText(n: number) { return n >= 1000 ? `${(n / 1000).toFixed(1)} km` : `${Math.max(10, Math.round(n / 10) * 10)} m`; }
function timeText(s: number) { const m = Math.max(1, Math.round(s / 60)); return m < 60 ? `${m} min` : `${Math.floor(m / 60)} hr ${m % 60} min`; }
function money(n?: number | null) { return n == null ? "—" : `₱${Number(n).toLocaleString("en-PH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function instruction(step?: Step) { if (!step) return "Continue straight"; const t = step.maneuver?.type; const d = step.maneuver?.modifier?.replace(/-/g, " "); const road = step.name ? ` onto ${step.name}` : ""; if (t === "arrive") return "Arrive at destination"; if (t === "depart") return `Head ${d ?? "straight"}${road}`; if (t === "roundabout" || t === "rotary") return `Take the roundabout${road}`; if (t === "merge") return `Merge ${d ?? "ahead"}${road}`; if (t === "fork") return `Keep ${d ?? "straight"}${road}`; if (t === "turn") return `Turn ${d ?? "ahead"}${road}`; return `Continue ${d ?? "straight"}${road}`; }
function icon(step?: Step) { const t = step?.maneuver?.type; const d = step?.maneuver?.modifier; if (t === "arrive") return "⌂"; if (t === "roundabout" || t === "rotary") return "↻"; if (d?.includes("left")) return "↰"; if (d?.includes("right")) return "↱"; return "↑"; }
function nearest(point: Point, line: [number, number][]) { let best = { d: Infinity, along: 0 }; let along = 0; const lat = 111320; const lon = Math.cos(point.latitude * Math.PI / 180) * lat; for (let i = 1; i < line.length; i++) { const a = line[i - 1], b = line[i]; const ax = (a[0] - point.longitude) * lon, ay = (a[1] - point.latitude) * lat; const bx = (b[0] - point.longitude) * lon, by = (b[1] - point.latitude) * lat; const dx = bx - ax, dy = by - ay; const den = dx * dx + dy * dy; const t = den ? Math.max(0, Math.min(1, -(ax * dx + ay * dy) / den)) : 0; const q = { longitude: a[0] + (b[0] - a[0]) * t, latitude: a[1] + (b[1] - a[1]) * t }; const seg = meters({ latitude: a[1], longitude: a[0] }, { latitude: b[1], longitude: b[0] }); const d = meters(point, q); if (d < best.d) best = { d, along: along + seg * t }; along += seg; } return best; }
function loadMapLibre() { return new Promise<void>((resolve, reject) => { if (typeof window === "undefined") return reject(new Error("Browser required")); if (window.maplibregl) return resolve(); const existing = document.querySelector<HTMLScriptElement>('script[data-maplibre="true"]'); if (existing) { existing.addEventListener("load", () => resolve(), { once: true }); existing.addEventListener("error", () => reject(new Error("Map failed to load")), { once: true }); return; } if (!document.querySelector('link[data-maplibre="true"]')) { const css = document.createElement("link"); css.rel = "stylesheet"; css.href = "https://unpkg.com/maplibre-gl@5.9.0/dist/maplibre-gl.css"; css.dataset.maplibre = "true"; document.head.appendChild(css); } const script = document.createElement("script"); script.src = "https://unpkg.com/maplibre-gl@5.9.0/dist/maplibre-gl.js"; script.async = true; script.dataset.maplibre = "true"; script.onload = () => resolve(); script.onerror = () => reject(new Error("Map failed to load. Check the browser network/CSP settings.")); document.body.appendChild(script); }); }

export function RiderNavigation({ initialJob, onBack }: { initialJob: Job; onBack?: () => void }) {
  const router = useRouter();
  const [job, setJob] = useState(initialJob); const [position, setPosition] = useState<Point | null>(null); const [heading, setHeading] = useState(0); const [route, setRoute] = useState<Route | null>(null); const [progress, setProgress] = useState(0); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [offRoute, setOffRoute] = useState(false); const [follow, setFollow] = useState(true); const [voice, setVoice] = useState(false); const [busy, setBusy] = useState(false); const [ready, setReady] = useState(false);
  const node = useRef<HTMLDivElement>(null); const map = useRef<any>(null); const marker = useRef<any>(null); const routeRef = useRef<Route | null>(null); const lastRoute = useRef(0); const requestId = useRef(0); const manual = useRef(false); const fallbackUsed = useRef(false);
  const destination = useMemo<Point | null>(() => { const drop = job.status === "picked_up" || job.status === "delivering"; const lat = drop ? job.dropoffLatitude : job.pickupLatitude; const lng = drop ? job.dropoffLongitude : job.pickupLongitude; return lat != null && lng != null ? { latitude: Number(lat), longitude: Number(lng) } : null; }, [job]);
  const steps = useMemo(() => (route?.legs ?? []).flatMap(x => x.steps ?? []), [route]);
  const stepInfo = useMemo(() => { let offset = 0; return steps.map(s => { const x = { step: s, start: offset }; offset += s.distance ?? 0; return x; }); }, [steps]);
  const current = useMemo(() => stepInfo.find(x => x.start + (x.step.distance ?? 0) > progress + 8)?.step ?? stepInfo.at(-1)?.step, [stepInfo, progress]);
  const nextDistance = useMemo(() => { const x = stepInfo.find(v => v.step === current); return x && current ? Math.max(0, x.start + (current.distance ?? 0) - progress) : null; }, [stepInfo, current, progress]);
  const remaining = Math.max(0, (route?.distance ?? 0) - progress); const eta = Math.max(0, (route?.duration ?? 0) - (progress / Math.max(route?.distance ?? 1, 1)) * (route?.duration ?? 0));
  const codAmount = job.codAmount ?? job.order?.codAmount ?? job.order?.amountDue ?? job.order?.totalAmount;
  const deliveryFee = job.deliveryFee ?? job.order?.deliveryFee ?? job.finalFare ?? job.estimatedFare;

  const calculateRoute = useCallback(async (force = false) => { if (!position || !destination) return; const now = Date.now(); if (!force && now - lastRoute.current < 4000) return; lastRoute.current = now; const id = ++requestId.current; setLoading(true); setError(null); try { const q = new URLSearchParams({ originLat: String(position.latitude), originLng: String(position.longitude), destLat: String(destination.latitude), destLng: String(destination.longitude) }); const data = await apiFetch<RouteResponse>(`/rider/route?${q}`, undefined); const next = data?.routes?.[0]; if (!next?.geometry?.coordinates?.length) throw new Error(data?.distanceMeters ? "Route geometry is unavailable" : "No drivable route found"); if (id !== requestId.current) return; routeRef.current = next; setRoute(next); setOffRoute(false); } catch (e) { if (id === requestId.current) setError(e instanceof Error ? e.message : "Routing unavailable"); } finally { if (id === requestId.current) setLoading(false); } }, [destination, position]);

  useEffect(() => { loadMapLibre().then(() => setReady(true)).catch(e => setError(e.message)); }, []);
  useEffect(() => { if (!ready || !node.current || map.current) return; const ml = window.maplibregl; if (!ml) { setError("Map library is unavailable"); return; } const p = position ?? destination ?? { latitude: 14.5995, longitude: 120.9842 }; const m = new ml.Map({ container: node.current, style: MAP_STYLE, center: [p.longitude, p.latitude], zoom: 16.5, attributionControl: true, preserveDrawingBuffer: false }); map.current = m; m.addControl(new ml.NavigationControl({ showCompass: false }), "bottom-right");
    const ensureRouteLayer = () => { if (!m.getSource("route")) m.addSource("route", { type: "geojson", data: { type: "Feature", properties: {}, geometry: { type: "LineString", coordinates: [] } } }); if (!m.getLayer("route-casing")) m.addLayer({ id: "route-casing", type: "line", source: "route", paint: { "line-color": "#fff", "line-width": 11 } }); if (!m.getLayer("route")) m.addLayer({ id: "route", type: "line", source: "route", paint: { "line-color": "#4285F4", "line-width": 6 } }); };
    const applyRoute = () => { if (!routeRef.current?.geometry?.coordinates?.length) return; const source = m.getSource("route") as any; if (source) source.setData({ type: "Feature", properties: {}, geometry: { type: "LineString", coordinates: routeRef.current.geometry.coordinates } }); };
    m.once("load", () => { ensureRouteLayer(); m.resize(); applyRoute(); });
    m.on("error", (event: any) => { const message = event?.error?.message ?? "Map tiles or style failed to load"; if (!fallbackUsed.current && /style|source|tile|network|fetch/i.test(message)) { fallbackUsed.current = true; m.setStyle(MAP_FALLBACK_STYLE); m.once("style.load", () => { ensureRouteLayer(); m.resize(); applyRoute(); }); } else { setError(`Map failed to load: ${message}`); } });
    const resize = () => m.resize(); window.requestAnimationFrame(resize); window.setTimeout(resize, 250); window.setTimeout(resize, 1000);
    m.on("dragstart", () => { manual.current = true; setFollow(false); }); m.on("zoomstart", () => { manual.current = true; setFollow(false); }); return () => { marker.current?.remove(); m.remove(); map.current = null; }; }, [ready]);
  useEffect(() => { const m = map.current; if (!m || !route?.geometry?.coordinates?.length) return; const update = () => { const source = m.getSource("route") as any; if (source) source.setData({ type: "Feature", properties: {}, geometry: { type: "LineString", coordinates: route.geometry!.coordinates! } }); }; if (m.isStyleLoaded()) update(); else m.once("load", update); }, [route]);
  useEffect(() => { const m = map.current; const ml = window.maplibregl; if (!m || !ml || !position) return; const xy: [number, number] = [position.longitude, position.latitude]; if (!marker.current) { const el = document.createElement("div"); el.className = "flex h-12 w-12 items-center justify-center"; el.innerHTML = `<div style="width:46px;height:46px;display:flex;align-items:center;justify-content:center;filter:drop-shadow(0 2px 3px rgba(0,0,0,.35));transform:rotate(${heading}deg)"><svg width="40" height="40" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><circle cx="17" cy="47" r="7" fill="#111827"/><circle cx="47" cy="47" r="7" fill="#111827"/><path d="M17 47l9-19h13l8 19M26 28l7 10h12M33 38l-8 0M39 28l5-7h7" stroke="#4285F4" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><circle cx="39" cy="20" r="5" fill="#4285F4"/><path d="M39 20h8" stroke="#111827" stroke-width="4" stroke-linecap="round"/></svg></div>`; marker.current = new ml.Marker({ element: el, anchor: "center" }).setLngLat(xy).addTo(m); } else { marker.current.setLngLat(xy); const bike = marker.current.getElement()?.firstElementChild as HTMLElement | null; if (bike) bike.style.transform = `rotate(${heading}deg)`; } if (follow && !manual.current) m.easeTo({ center: xy, zoom: 17.4, bearing: heading, pitch: 48, duration: 500, essential: true }); }, [ready, position, heading, follow]);
  useEffect(() => { if (!route?.geometry?.coordinates?.length || !position) return; const n = nearest(position, route.geometry.coordinates); setProgress(n.along); const off = n.d > 60 && (!destination || meters(position, destination) > 40); setOffRoute(off); if (off) void calculateRoute(true); }, [position, route, destination, calculateRoute]);
  useEffect(() => { if (!position || !destination) return; void calculateRoute(!route); const id = window.setInterval(() => { if (routeRef.current) void calculateRoute(false); }, 5000); return () => window.clearInterval(id); }, [position, destination, route, calculateRoute]);
  useEffect(() => { if (!voice || !current || (nextDistance ?? 9999) > 120 || !("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(instruction(current))); }, [voice, current, nextDistance]);
  useEffect(() => { if (!navigator.geolocation) { setError("Location is unavailable in this browser"); return; } const id = navigator.geolocation.watchPosition(p => { const next = { latitude: p.coords.latitude, longitude: p.coords.longitude }; setPosition(next); if (p.coords.heading != null && p.coords.heading >= 0) setHeading(p.coords.heading); void apiFetch("/rider/location", { method: "POST", body: JSON.stringify({ ...next, heading: p.coords.heading ?? undefined, speed: p.coords.speed ?? undefined, accuracy: p.coords.accuracy ?? undefined }) }).catch(() => undefined); }, e => setError(e.message), { enableHighAccuracy: true, maximumAge: 1500, timeout: 10000 }); return () => window.navigator.geolocation.clearWatch(id); }, []);

  const recenter = () => { manual.current = false; setFollow(true); if (map.current && position) map.current.easeTo({ center: [position.longitude, position.latitude], zoom: 17.4, bearing: heading, pitch: 48, duration: 450, essential: true }); };
  const handleBack = () => { if (onBack) onBack(); else router.push("/dashboard"); };
  const advance = async () => { const next = NEXT[job.status]; if (!next) return; setBusy(true); try { await apiFetch(`/rider/jobs/${job.id}/status`, { method: "PATCH", body: JSON.stringify({ status: next }) }); setJob({ ...job, status: next }); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update delivery"); } finally { setBusy(false); } };
  const arrive = new Date(Date.now() + eta * 1000).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }); const destinationText = job.status === "picked_up" || job.status === "delivering" ? job.dropoffAddress : job.pickupAddress;

  return <div className="relative h-[100dvh] min-h-[680px] w-full overflow-hidden bg-[#E9E6DF] text-[#1f2937]">
    <div ref={node} className="absolute inset-0 min-h-full min-w-full" />
    <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-black/30 via-transparent to-black/15" />
    <div className="absolute left-3 right-3 top-3 z-20 flex gap-2"><button onClick={handleBack} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-white shadow-xl"><ArrowLeft size={19}/></button><div className="min-w-0 flex-1 rounded-[20px] bg-[#111827] text-white shadow-xl"><div className="flex items-center gap-3 px-4 py-3"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white text-3xl font-black text-[#111827]">{icon(current)}</div><div className="min-w-0 flex-1"><div className="text-[22px] font-black leading-6">{nextDistance != null ? distanceText(nextDistance) : "—"}</div><div className="truncate text-[13px] font-semibold text-white/75">{instruction(current)}</div></div><button onClick={() => setVoice(v => !v)} className="rounded-full p-2">{voice ? <Volume2 size={19}/> : <VolumeX size={19}/>}</button></div></div></div>
    <div className="absolute right-3 top-[78px] z-20 flex flex-col gap-2"><button onClick={recenter} className={`flex h-11 w-11 items-center justify-center rounded-full bg-white shadow-xl ${follow ? "text-[#4285F4]" : "text-[#555]"}`}><LocateFixed size={19}/></button><button onClick={() => void calculateRoute(true)} className="flex h-11 w-11 items-center justify-center rounded-full bg-white text-[#555] shadow-xl"><RefreshCw size={18} className={loading ? "animate-spin" : ""}/></button></div>
    <div className="absolute bottom-0 left-0 right-0 z-20 rounded-t-[28px] bg-white p-4 shadow-[0_-10px_35px_rgba(0,0,0,.18)]"><div className="mx-auto mb-3 h-1.5 w-12 rounded-full bg-black/10"/><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-xs font-bold uppercase tracking-wider text-[#888]">{job.status === "picked_up" || job.status === "delivering" ? "Deliver to" : "Pickup at"}</div><div className="mt-1 truncate text-lg font-black">{destinationText}</div><div className="mt-1 flex items-center gap-2 text-sm text-[#666]"><span>{route ? distanceText(remaining) : "Calculating route…"}</span><span>•</span><span>{route ? timeText(eta) : "—"}</span><span>•</span><span>ETA {arrive}</span></div></div><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-[#F7F2EC] text-[#111827]"><Navigation size={21}/></div></div>{error ? <div className="mt-3 rounded-xl bg-red-50 px-3 py-2 text-sm font-semibold text-red-700">{error}</div> : null}{offRoute ? <div className="mt-3 rounded-xl bg-amber-50 px-3 py-2 text-sm font-semibold text-amber-800">You are off route. Recalculating…</div> : null}<div className="mt-4 rounded-2xl bg-[#F7F2EC] px-4 py-3"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-[#756D66]">COD Amount</span><span className="text-lg font-black text-[#111827]">{money(codAmount)}</span></div><div className="mt-2 flex items-center justify-between border-t border-black/5 pt-2"><span className="text-sm font-semibold text-[#756D66]">Delivery Fee</span><span className="text-lg font-black text-[#111827]">{money(deliveryFee)}</span></div></div><div className="mt-3 flex gap-2"><button onClick={advance} disabled={busy || !NEXT[job.status]} className="flex-1 rounded-2xl bg-[#111827] px-4 py-3.5 text-sm font-black text-white disabled:opacity-50">{busy ? "Updating…" : ACTION[job.status] ?? "Delivery complete"}</button>{job.order?.customer?.phoneNumber ? <a href={`tel:${job.order.customer.phoneNumber}`} className="flex h-12 w-12 items-center justify-center rounded-2xl border border-black/10"><Phone size={19}/></a> : null}</div></div>
  </div>;
}
