"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, LocateFixed, Navigation, Phone, RefreshCw, Volume2, VolumeX } from "lucide-react";
import { apiFetch } from "@/lib/api";

type Coordinate = { latitude: number; longitude: number };
type Profile = { id: string; status: "offline" | "online" | "busy" | "suspended"; rating: number; completedJobs: number; user: { name: string; email: string; role: string }; locations: Coordinate[] };
type Job = { id: string; status: string; pickupAddress: string; pickupLatitude?: number | null; pickupLongitude?: number | null; dropoffAddress: string; dropoffLatitude?: number | null; dropoffLongitude?: number | null; estimatedFare?: number | null; finalFare?: number | null; estimatedDurationMinutes?: number | null; distanceKm?: number | null; order?: { orderNumber: string; quantity?: number; customer: { name: string; phoneNumber?: string | null } } | null };
type Maneuver = { type?: string; modifier?: string; location?: [number, number] };
type RouteStep = { distance?: number; duration?: number; name?: string; maneuver?: Maneuver };
type Route = { distance?: number; duration?: number; geometry?: { coordinates?: [number, number][] }; legs?: { steps?: RouteStep[] }[] };

declare global { interface Window { maplibregl?: any } }
const ACTIVE = ["requested", "searching_rider", "assigned", "accepted", "pickup_started", "picked_up", "delivering"];
const NEXT: Record<string, string> = { assigned: "accepted", accepted: "pickup_started", pickup_started: "picked_up", picked_up: "delivering", delivering: "delivered" };
const LABEL: Record<string, string> = { assigned: "Go to Pickup", accepted: "Confirm Pickup", pickup_started: "Confirm Pickup", picked_up: "Start Delivery", delivering: "Complete Delivery" };

function validPoint(point?: Coordinate | null) { return !!point && Number.isFinite(point.latitude) && Number.isFinite(point.longitude); }
function distanceMeters(a: Coordinate, b: Coordinate) { const r = 6371000; const p1 = a.latitude * Math.PI / 180; const p2 = b.latitude * Math.PI / 180; const dp = (b.latitude - a.latitude) * Math.PI / 180; const dl = (b.longitude - a.longitude) * Math.PI / 180; const h = Math.sin(dp / 2) ** 2 + Math.cos(p1) * Math.cos(p2) * Math.sin(dl / 2) ** 2; return 2 * r * Math.asin(Math.sqrt(h)); }
function bearing(a: Coordinate, b: Coordinate) { const p1 = a.latitude * Math.PI / 180; const p2 = b.latitude * Math.PI / 180; const dl = (b.longitude - a.longitude) * Math.PI / 180; return (Math.atan2(Math.sin(dl) * Math.cos(p2), Math.cos(p1) * Math.sin(p2) - Math.sin(p1) * Math.cos(p2) * Math.cos(dl)) * 180 / Math.PI + 360) % 360; }
function formatDistance(m?: number | null) { if (m == null || !Number.isFinite(m)) return "—"; return m >= 1000 ? `${(m / 1000).toFixed(1)} km` : `${Math.max(10, Math.round(m / 10) * 10)} m`; }
function formatTime(seconds?: number | null) { if (seconds == null || !Number.isFinite(seconds)) return "—"; const mins = Math.max(1, Math.round(seconds / 60)); return mins < 60 ? `${mins} min` : `${Math.floor(mins / 60)} hr ${mins % 60} min`; }
function stepText(step?: RouteStep) { if (!step) return "Continue straight"; const type = step.maneuver?.type; const modifier = step.maneuver?.modifier?.replace(/-/g, " "); const road = step.name ? ` onto ${step.name}` : ""; if (type === "arrive") return "Arrive at destination"; if (type === "depart") return `Head ${modifier ?? "straight"}${road}`; if (type === "roundabout" || type === "rotary") return `Take the roundabout${road}`; if (type === "merge") return `Merge ${modifier ?? "ahead"}${road}`; if (type === "fork") return `Keep ${modifier ?? "straight"}${road}`; if (type === "continue" || type === "new name") return `Continue ${modifier ?? "straight"}${road}`; if (type === "turn") return `Turn ${modifier ?? "ahead"}${road}`; return `${type?.replace(/_/g, " ") ?? "Continue straight"}${modifier ? ` ${modifier}` : ""}${road}`; }
function maneuverGlyph(step?: RouteStep) { const type = step?.maneuver?.type; const modifier = step?.maneuver?.modifier; if (type === "arrive") return "⌂"; if (type === "roundabout" || type === "rotary") return "↻"; if (modifier?.includes("left")) return "↰"; if (modifier?.includes("right")) return "↱"; return "↑"; }
function projectPoint(point: Coordinate, a: [number, number], b: [number, number]) { const latScale = 111320; const lonScale = Math.cos(point.latitude * Math.PI / 180) * latScale; const px = (point.longitude - a[0]) * lonScale; const py = (point.latitude - a[1]) * latScale; const bx = (b[0] - a[0]) * lonScale; const by = (b[1] - a[1]) * latScale; const denom = bx * bx + by * by; const t = denom ? Math.max(0, Math.min(1, (px * bx + py * by) / denom)) : 0; const lon = a[0] + (b[0] - a[0]) * t; const lat = a[1] + (b[1] - a[1]) * t; return { coordinate: { latitude: lat, longitude: lon }, t }; }
function nearestOnRoute(point: Coordinate, coords: [number, number][]) { let best = { distance: Infinity, index: 0, t: 0, along: 0, coordinate: point as Coordinate }; let along = 0; for (let i = 1; i < coords.length; i++) { const a = coords[i - 1]; const b = coords[i]; const segment = distanceMeters({ latitude: a[1], longitude: a[0] }, { latitude: b[1], longitude: b[0] }); const projected = projectPoint(point, a, b); const d = distanceMeters(point, projected.coordinate); if (d < best.distance) best = { distance: d, index: i - 1, t: projected.t, along: along + segment * projected.t, coordinate: projected.coordinate }; along += segment; } return best; }
function useMapLibre() { const [ready, setReady] = useState(false); useEffect(() => { if (typeof window === "undefined") return; if (window.maplibregl) { setReady(true); return; } const css = document.createElement("link"); css.rel = "stylesheet"; css.href = "https://unpkg.com/maplibre-gl@5.9.0/dist/maplibre-gl.css"; document.head.appendChild(css); const script = document.createElement("script"); script.src = "https://unpkg.com/maplibre-gl@5.9.0/dist/maplibre-gl.js"; script.async = true; script.onload = () => setReady(true); document.body.appendChild(script); return () => { script.remove(); css.remove(); }; }, []); return ready; }

export function RiderAppV9() {
  const [profile, setProfile] = useState<Profile | null>(null); const [jobs, setJobs] = useState<Job[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [location, setLocation] = useState<Coordinate | null>(null); const [heading, setHeading] = useState(0); const [tab, setTab] = useState<"orders" | "map">("orders"); const [navigating, setNavigating] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const hydrate = useCallback(async () => { const [nextProfile, nextJobs] = await Promise.all([apiFetch<Profile>("/rider/me"), apiFetch<Job[]>("/rider/jobs")]); setProfile(nextProfile); setJobs(nextJobs); const delivering = nextJobs.find(job => job.status === "delivering"); const active = nextJobs.find(job => ACTIVE.includes(job.status)); setSelectedId(delivering?.id ?? active?.id ?? null); if (delivering) { setTab("map"); setNavigating(true); } }, []);
  useEffect(() => { hydrate().catch(e => setError(e instanceof Error ? e.message : "Unable to load rider data")); }, [hydrate]);
  useEffect(() => { if (!profile || profile.status === "offline" || profile.status === "suspended" || !navigator.geolocation) return; const id = navigator.geolocation.watchPosition(position => { const coords = { latitude: position.coords.latitude, longitude: position.coords.longitude }; setLocation(coords); if (position.coords.heading != null && position.coords.heading >= 0) setHeading(position.coords.heading); void apiFetch("/rider/location", { method: "POST", body: JSON.stringify({ ...coords, heading: position.coords.heading ?? undefined, speed: position.coords.speed ?? undefined, accuracy: position.coords.accuracy ?? undefined }) }).catch(() => undefined); }, geoError => setError(geoError.message), { enableHighAccuracy: true, maximumAge: 1500, timeout: 10000 }); return () => navigator.geolocation.clearWatch(id); }, [profile?.status]);
  const activeJobs = useMemo(() => jobs.filter(job => ACTIVE.includes(job.status)), [jobs]); const deliveredJobs = useMemo(() => jobs.filter(job => job.status === "delivered"), [jobs]); const selectedJob = jobs.find(job => job.id === selectedId) ?? activeJobs[0] ?? null;
  async function toggleOnline() { if (!profile || profile.status === "suspended") return; setBusy(true); setError(null); try { setProfile(await apiFetch<Profile>("/rider/status", { method: "PATCH", body: JSON.stringify({ status: profile.status === "online" ? "offline" : "online" }) })); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update status"); } finally { setBusy(false); } }
  async function advance(job: Job) { const nextStatus = NEXT[job.status]; if (!nextStatus) return; setBusy(true); setError(null); try { await apiFetch(`/rider/jobs/${job.id}/status`, { method: "PATCH", body: JSON.stringify({ status: nextStatus }) }); await hydrate(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update order"); } finally { setBusy(false); } }
  return <div className="min-h-[100dvh] bg-[#FFF6EC] text-[#241C18] -mx-4 -my-6 lg:-mx-8 lg:-my-8"><div className="mx-auto flex min-h-[100dvh] w-full max-w-[720px] flex-col bg-[#FFF6EC] lg:border-x lg:border-[#F0E4D6]">{error ? <div className="absolute left-3 right-3 top-3 z-[120] rounded-2xl border border-[#E8A881] bg-[#FFF0E3] px-4 py-3 text-xs font-semibold text-[#8A3E1D]">{error}</div> : null}<main className="flex-1 overflow-y-auto pb-20">{tab === "orders" ? <Orders profile={profile} jobs={activeJobs} delivered={deliveredJobs} busy={busy} onOnline={toggleOnline} onRefresh={hydrate} onNavigate={job => { setSelectedId(job.id); setTab("map"); setNavigating(true); }} onAdvance={advance}/> : selectedJob ? <NavigationScreen job={selectedJob} riderLocation={location ?? profile?.locations?.[0] ?? null} heading={heading} navigating={navigating} onBack={() => { setTab("orders"); setNavigating(false); }} onAdvance={advance} busy={busy}/> : <EmptyMap onBack={() => setTab("orders")}/>}</main><nav className="fixed bottom-0 left-1/2 z-50 flex w-full max-w-[720px] -translate-x-1/2 border-t border-[#F0E4D6] bg-white px-2 pb-2 pt-2"><button onClick={() => { setTab("orders"); setNavigating(false); }} className={`flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black ${tab === "orders" ? "text-[#F4581D]" : "text-[#8A817A]"}`}>🧾<span>Orders</span></button><button onClick={() => { setTab("map"); setNavigating(true); }} className={`flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black ${tab === "map" ? "text-[#F4581D]" : "text-[#8A817A]"}`}>🗺️<span>Map</span></button><button className="flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black text-[#8A817A]">📊<span>Earnings</span></button><button className="flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black text-[#8A817A]">👤<span>Profile</span></button></nav></div></div>;
}

function Orders({ profile, jobs, delivered, busy, onOnline, onRefresh, onNavigate, onAdvance }: { profile: Profile | null; jobs: Job[]; delivered: Job[]; busy: boolean; onOnline: () => void; onRefresh: () => void; onNavigate: (job: Job) => void; onAdvance: (job: Job) => void }) { return <div className="pt-5"><div className="mx-5 flex items-center justify-between rounded-full bg-white px-4 py-3 shadow-sm ring-1 ring-[#F0E4D6]"><button disabled={busy} onClick={onOnline} className={`rounded-full px-3 py-1.5 text-xs font-black ${profile?.status === "online" ? "bg-[#E4F6EB] text-[#1FA35A]" : "bg-[#F6EEE7] text-[#8A817A]`}>{profile?.status === "online" ? "● Online" : "○ Offline"}</button><span className="text-[11px] font-bold text-[#8A817A]">{jobs.length} active · {(profile?.rating ?? 5).toFixed(1)} ⭐</span></div><Title text="Active Orders" count={jobs.length}/>{jobs.length ? jobs.map(job => <OrderCard key={job.id} job={job} busy={busy} onNavigate={onNavigate} onAdvance={onAdvance}/>) : <div className="mx-5 rounded-[22px] bg-white p-7 text-center ring-1 ring-[#F0E4D6]"><div className="text-3xl">🥟</div><div className="mt-2 text-sm font-black">{profile?.status === "online" ? "Waiting for an order" : "You're offline"}</div></div>}<Title text="Recent Orders"/><div className="mx-5 rounded-[22px] bg-white ring-1 ring-[#F0E4D6]">{delivered.length ? delivered.slice(0, 8).map((job, index) => <div key={job.id} className={`flex items-center gap-3 px-4 py-3.5 ${index < Math.min(7, delivered.length - 1) ? "border-b border-[#F0E4D6]" : ""}`}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#FFE3D2] text-xl">🥟</div><div className="min-w-0 flex-1"><div className="truncate text-[13px] font-black">{job.order?.customer.name ?? "Customer"}</div><div className="truncate text-[11px] text-[#8A817A]">{job.dropoffAddress}</div></div><div className="text-right"><div className="text-xs font-black text-[#1FA35A]">₱{Number(job.finalFare ?? job.estimatedFare ?? 0).toFixed(0)}</div><div className="text-[10px] text-[#8A817A]">Delivered</div></div></div>) : <div className="p-5 text-center text-xs text-[#8A817A]">No deliveries completed yet.</div>}</div><button onClick={onRefresh} className="mx-5 mt-3 flex w-[calc(100%-40px)] items-center justify-center gap-2 rounded-2xl bg-white py-3 text-xs font-black ring-1 ring-[#F0E4D6]"><RefreshCw size={14}/>Refresh</button></div>; }
function OrderCard({ job, busy, onNavigate, onAdvance }: { job: Job; busy: boolean; onNavigate: (job: Job) => void; onAdvance: (job: Job) => void }) { const dropoff = job.status === "picked_up" || job.status === "delivering"; const fare = Number(job.finalFare ?? job.estimatedFare ?? 0); return <div className="mx-5 mb-3 rounded-[22px] border-[1.5px] border-[#F4581D] bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="rounded-[10px] bg-[#FFE3D2] px-2.5 py-1.5 text-[11px] font-extrabold text-[#D9430F]">{job.status === "delivering" ? "🧭 Navigating" : job.status === "assigned" ? "🕐 New Order" : "🚴 Current Order"}</span><span className="text-xs font-extrabold text-[#8A817A]">#{job.order?.orderNumber ?? job.id.slice(-6).toUpperCase()}</span></div><div className="mt-4 flex items-start gap-3.5"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#FFE3D2] text-[26px]">🥟</div><div className="min-w-0 flex-1"><div className="text-[15px] font-extrabold">👤 {job.order?.customer.name ?? "Customer"}</div><div className="mt-1 text-[13px] leading-[18px] text-[#5C5450]">📍 {dropoff ? job.dropoffAddress : job.pickupAddress}</div></div></div><div className="mt-4 flex gap-2"><div className="flex-1"><div className="text-[19px] font-black">₱{fare.toFixed(0)}</div></div><button disabled={busy} onClick={() => onNavigate(job)} className="rounded-2xl border border-[#F4581D] bg-white px-3 py-3 text-[12px] font-black text-[#F4581D]"><Navigation size={14} className="mr-1 inline"/>Navigate</button><button disabled={busy || !NEXT[job.status]} onClick={() => onAdvance(job)} className="rounded-2xl bg-[#F4581D] px-3 py-3 text-[12px] font-black text-white">{busy ? "Updating…" : LABEL[job.status] ?? "Open Order"}</button></div>{job.order?.customer.phoneNumber ? <a href={`tel:${job.order.customer.phoneNumber}`} className="mt-2 flex items-center justify-center gap-2 rounded-xl bg-[#F6EEE7] py-2 text-xs font-black text-[#5C5450]"><Phone size={13}/>Call customer</a> : null}</div>; }
function Title({ text, count }: { text: string; count?: number }) { return <div className="mt-6 mb-3 flex items-center justify-between px-5"><div className="text-[15px] font-black">{text}</div>{count !== undefined ? <div className="rounded-full bg-[#FFE3D2] px-2.5 py-1 text-[10px] font-black text-[#D9430F]">{count}</div> : null}</div>; }
function EmptyMap({ onBack }: { onBack: () => void }) { return <div className="flex min-h-[70dvh] items-center justify-center p-6"><div className="text-center"><div className="text-4xl">🗺️</div><div className="mt-2 font-black">No active delivery</div><button onClick={onBack} className="mt-4 rounded-2xl bg-[#F4581D] px-5 py-3 text-xs font-black text-white">Back to orders</button></div></div>; }

function NavigationScreen({ job, riderLocation, heading, navigating, onBack, onAdvance, busy }: { job: Job; riderLocation: Coordinate | null; heading: number; navigating: boolean; onBack: () => void; onAdvance: (job: Job) => void; busy: boolean }) {
  const mapReady = useMapLibre(); const mapNode = useRef<HTMLDivElement | null>(null); const mapRef = useRef<any>(null); const markerRef = useRef<any>(null); const routeRef = useRef<Route | null>(null); const routeCoordsRef = useRef<[number, number][]>([]); const lastRouteAtRef = useRef(0); const requestRef = useRef(0); const userInteractingRef = useRef(false); const [route, setRoute] = useState<Route | null>(null); const [routeLoading, setRouteLoading] = useState(false); const [routeError, setRouteError] = useState<string | null>(null); const [follow, setFollow] = useState(true); const [voice, setVoice] = useState(false); const [progress, setProgress] = useState(0); const [offRoute, setOffRoute] = useState(false); const [started, setStarted] = useState(false); const [now, setNow] = useState(Date.now());
  const destination = useMemo<Coordinate | null>(() => { const dropoff = job.status === "picked_up" || job.status === "delivering"; const latitude = dropoff ? job.dropoffLatitude : job.pickupLatitude; const longitude = dropoff ? job.dropoffLongitude : job.pickupLongitude; return latitude != null && longitude != null ? { latitude: Number(latitude), longitude: Number(longitude) } : null; }, [job]);
  const routeDistance = route?.distance ?? 0; const routeDuration = route?.duration ?? 0; const steps = useMemo(() => (route?.legs ?? []).flatMap(leg => leg.steps ?? []), [route]);
  const stepOffsets = useMemo(() => { let offset = 0; return steps.map(step => { const item = { step, start: offset }; offset += step.distance ?? 0; return item; }); }, [steps]);
  const upcoming = useMemo(() => { if (!stepOffsets.length) return undefined; return stepOffsets.find(item => item.start + (item.step.distance ?? 0) > progress + 8)?.step ?? stepOffsets[stepOffsets.length - 1]?.step; }, [stepOffsets, progress]);
  const nextStepDistance = useMemo(() => { if (!upcoming) return null; const item = stepOffsets.find(entry => entry.step === upcoming); if (!item) return null; return Math.max(0, (item.start + (upcoming.distance ?? 0)) - progress); }, [stepOffsets, upcoming, progress]);
  const eta = useMemo(() => Math.max(0, routeDuration - (progress / Math.max(routeDistance, 1)) * routeDuration), [routeDistance, routeDuration, progress]);
  const destinationDistance = useMemo(() => riderLocation && destination ? distanceMeters(riderLocation, destination) : routeDistance, [riderLocation, destination, routeDistance]);

  const fetchRoute = useCallback(async (force = false) => { if (!riderLocation || !destination || !validPoint(riderLocation) || !validPoint(destination)) return; const nowMs = Date.now(); if (!force && nowMs - lastRouteAtRef.current < 4000) return; const requestId = ++requestRef.current; lastRouteAtRef.current = nowMs; setRouteLoading(true); setRouteError(null); try { const params = new URLSearchParams({ originLat: String(riderLocation.latitude), originLng: String(riderLocation.longitude), destLat: String(destination.latitude), destLng: String(destination.longitude) }); const response = await fetch(`/api/rider/route?${params.toString()}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload?.error ?? "Unable to calculate route"); if (requestId !== requestRef.current) return; const next = payload?.routes?.[0] as Route | undefined; if (!next?.geometry?.coordinates?.length) throw new Error("No drivable route found"); routeRef.current = next; routeCoordsRef.current = next.geometry.coordinates; setRoute(next); setProgress(0); setOffRoute(false); setStarted(true); } catch (e) { if (requestId === requestRef.current) setRouteError(e instanceof Error ? e.message : "Unable to calculate route"); } finally { if (requestId === requestRef.current) setRouteLoading(false); } }, [destination, riderLocation]);

  useEffect(() => { if (!mapReady || !mapNode.current || mapRef.current) return; const maplibregl = window.maplibregl; const initial = riderLocation ?? destination ?? { latitude: 14.5995, longitude: 120.9842 }; const map = new maplibregl.Map({ container: mapNode.current, style: "https://tiles.openfreemap.org/styles/liberty", center: [initial.longitude, initial.latitude], zoom: 16, attributionControl: true }); mapRef.current = map; map.addControl(new maplibregl.NavigationControl({ showCompass: false }), "bottom-right"); map.on("load", () => { map.addSource("route", { type: "geojson", data: { type: "Feature", properties: {}, geometry: { type: "LineString", coordinates: [] } } }); map.addLayer({ id: "route-casing", type: "line", source: "route", paint: { "line-color": "#ffffff", "line-width": 10, "line-opacity": 0.95 } }); map.addLayer({ id: "route-line", type: "line", source: "route", paint: { "line-color": "#4285F4", "line-width": 6, "line-opacity": 1 } }); }); map.on("dragstart", () => { userInteractingRef.current = true; setFollow(false); }); map.on("zoomstart", () => { userInteractingRef.current = true; setFollow(false); }); return () => { markerRef.current?.remove(); map.remove(); mapRef.current = null; }; }, [mapReady]);
  useEffect(() => { const map = mapRef.current; if (!map || !route?.geometry?.coordinates?.length) return; const apply = () => { const source = map.getSource("route"); if (source) source.setData({ type: "Feature", properties: {}, geometry: { type: "LineString", coordinates: route.geometry!.coordinates! } }); }; if (map.isStyleLoaded()) apply(); else map.once("load", apply); }, [route]);
  useEffect(() => { const map = mapRef.current; const maplibregl = window.maplibregl; if (!map || !maplibregl || !riderLocation) return; const lngLat: [number, number] = [riderLocation.longitude, riderLocation.latitude]; if (!markerRef.current) { const el = document.createElement("div"); el.className = "relative flex h-11 w-11 items-center justify-center"; el.innerHTML = `<div style="transform:rotate(${heading}deg);width:0;height:0;border-left:8px solid transparent;border-right:8px solid transparent;border-bottom:18px solid #4285F4;filter:drop-shadow(0 2px 3px rgba(0,0,0,.35))"></div><div style="position:absolute;width:13px;height:13px;border-radius:50%;background:#fff;box-shadow:0 1px 4px rgba(0,0,0,.35)"></div>`; markerRef.current = new maplibregl.Marker({ element: el, anchor: "center" }).setLngLat(lngLat).addTo(map); } else { markerRef.current.setLngLat(lngLat); const arrow = markerRef.current.getElement()?.firstElementChild as HTMLElement | null; if (arrow) arrow.style.transform = `rotate(${heading}deg)`; } if (follow && navigating && !userInteractingRef.current) { map.easeTo({ center: lngLat, zoom: 17.2, bearing: heading || map.getBearing(), pitch: 52, duration: 650, essential: true }); } }, [riderLocation, heading, follow, navigating]);
  useEffect(() => { if (!routeCoordsRef.current.length || !riderLocation) return; const nearest = nearestOnRoute(riderLocation, routeCoordsRef.current); setProgress(nearest.along); const threshold = 55; const isOff = nearest.distance > threshold && distanceMeters(riderLocation, destination ?? riderLocation) > 35; setOffRoute(isOff); if (isOff) void fetchRoute(true); }, [riderLocation, destination, fetchRoute]);
  useEffect(() => { if (!riderLocation || !destination) return; void fetchRoute(!route); const timer = window.setInterval(() => { if (routeRef.current) void fetchRoute(false); }, 5000); return () => window.clearInterval(timer); }, [riderLocation, destination, fetchRoute, route]);
  useEffect(() => { if (!voice || !upcoming || typeof window === "undefined" || !("speechSynthesis" in window)) return; const distance = nextStepDistance ?? 0; if (distance > 120) return; const text = stepText(upcoming); const utterance = new SpeechSynthesisUtterance(text); utterance.rate = 1; window.speechSynthesis.cancel(); window.speechSynthesis.speak(utterance); }, [voice, upcoming, nextStepDistance]);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 15000); return () => window.clearInterval(timer); }, []);

  const recenter = () => { setFollow(true); userInteractingRef.current = false; if (mapRef.current && riderLocation) mapRef.current.easeTo({ center: [riderLocation.longitude, riderLocation.latitude], zoom: 17.2, bearing: heading, pitch: 52, duration: 500, essential: true }); };
  const startNavigation = () => { setNavigating(true); setFollow(true); userInteractingRef.current = false; recenter(); };
  const remainingText = route ? formatDistance(Math.max(0, routeDistance - progress)) : formatDistance(destinationDistance);
  const instruction = upcoming ? stepText(upcoming) : routeLoading ? "Finding the best route…" : "Waiting for your location…";
  const statusText = offRoute ? "Recalculating route…" : routeError ? "Route unavailable" : routeLoading && !route ? "Calculating route…" : started ? "On route" : "Ready to navigate";

  return <div className="relative h-[calc(100dvh-80px)] min-h-[680px] overflow-hidden bg-[#E9E6DF] text-[#241C18]">
    <div ref={mapNode} className="absolute inset-0" />
    <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-black/35 via-transparent to-black/20" />
    <div className="absolute left-3 right-3 top-3 z-20 flex items-start gap-2">
      <button onClick={onBack} aria-label="Back" className="pointer-events-auto flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-white shadow-lg"><ArrowLeft size={19}/></button>
      <div className="min-w-0 flex-1 overflow-hidden rounded-[20px] bg-[#111827] text-white shadow-xl">
        <div className="flex items-center gap-3 px-4 py-3"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white text-3xl font-black text-[#111827]">{maneuverGlyph(upcoming)}</div><div className="min-w-0"><div className="text-[22px] font-black leading-6">{nextStepDistance != null ? formatDistance(nextStepDistance) : "—"}</div><div className="truncate text-[13px] font-semibold text-white/75">{instruction}</div></div><button onClick={() => setVoice(value => !value)} className="ml-auto rounded-full p-2 hover:bg-white/10" aria-label="Toggle voice">{voice ? <Volume2 size={19}/> : <VolumeX size={19}/>}</button></div>
      </div>
    </div>
    <div className="absolute right-3 top-[78px] z-20 flex flex-col gap-2">
      <button onClick={recenter} aria-label="Recenter" className={`flex h-11 w-11 items-center justify-center rounded-full bg-white shadow-lg ${follow ? "text-[#4285F4]" : "text-[#555]"}`}><LocateFixed size={19}/></button>
      <button onClick={() => void fetchRoute(true)} aria-label="Refresh route" className="flex h-11 w-11 items-center justify-center rounded-full bg-white shadow-lg"><RefreshCw size={17} className={routeLoading ? "animate-spin" : ""}/></button>
    </div>
    {offRoute || routeError ? <div className="absolute left-1/2 top-[128px] z-20 -translate-x-1/2 rounded-full bg-[#111827] px-4 py-2 text-[11px] font-black text-white shadow-lg">{statusText}</div> : null}
    <div className="absolute bottom-0 left-0 right-0 z-20 rounded-t-[28px] bg-white px-4 pb-5 pt-3 shadow-[0_-8px_30px_rgba(0,0,0,.16)]">
      <div className="mx-auto mb-3 h-1.5 w-10 rounded-full bg-[#D8D2CA]" />
      <div className="flex items-end justify-between gap-4">
        <div><div className="text-[30px] font-black leading-8">{formatTime(eta || routeDuration)}</div><div className="mt-1 text-xs font-bold text-[#756D66]">{formatDistance(Math.max(0, routeDistance - progress))} · {statusText}</div></div>
        <div className="text-right"><div className="text-xs font-bold uppercase tracking-[.12em] text-[#8A817A]">Arrive</div><div className="text-[17px] font-black">{new Date(now + Math.max(0, eta || routeDuration) * 1000).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</div></div>
      </div>
      <div className="mt-3 rounded-2xl bg-[#F5F7FA] px-3 py-2.5"><div className="flex items-center gap-2 text-xs font-bold"><Navigation size={14} className="text-[#4285F4]"/><span className="truncate">{job.status === "picked_up" || job.status === "delivering" ? job.dropoffAddress : job.pickupAddress}</span></div><div className="mt-1 text-[11px] text-[#8A817A]">{route?.legs?.[0]?.steps?.length ? `${route.legs[0].steps.length} navigation steps` : "Road route"}</div></div>
      <div className="mt-3 flex gap-2"><button onClick={startNavigation} className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-[#4285F4] py-3.5 text-sm font-black text-white shadow-sm"><Navigation size={16}/> {navigating ? "Following route" : "Start navigation"}</button><button disabled={busy || !NEXT[job.status]} onClick={() => onAdvance(job)} className="rounded-2xl bg-[#F4581D] px-4 py-3.5 text-xs font-black text-white">{busy ? "Updating…" : LABEL[job.status] ?? "Complete"}</button></div>
      {job.order?.customer.phoneNumber ? <a href={`tel:${job.order.customer.phoneNumber}`} className="mt-2 flex items-center justify-center gap-2 rounded-xl bg-[#F6EEE7] py-2.5 text-xs font-black text-[#5C5450]"><Phone size={13}/>Call customer</a> : null}
      <div className="mt-2 text-center text-[10px] font-semibold text-[#938A82]">Live navigation · route follows your location · automatic rerouting</div>
    </div>
  </div>;
}
