"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Bell, LocateFixed, Navigation, Phone, RefreshCw } from "lucide-react";
import { apiFetch } from "@/lib/api";

type Coordinate={latitude:number;longitude:number};
type Profile={id:string;status:"offline"|"online"|"busy"|"suspended";rating:number;completedJobs:number;user:{name:string;email:string;role:string};locations:Coordinate[]};
type Job={id:string;status:string;pickupAddress:string;pickupLatitude?:number|null;pickupLongitude?:number|null;dropoffAddress:string;dropoffLatitude?:number|null;dropoffLongitude?:number|null;estimatedFare?:number|null;finalFare?:number|null;estimatedDurationMinutes?:number|null;distanceKm?:number|null;order?:{orderNumber:string;quantity?:number;customer:{name:string;phoneNumber?:string|null}}|null};
type Step={distance?:number;duration?:number;name?:string;maneuver?:{type?:string;modifier?:string}};
type Route={distance:number;duration:number;geometry?:{coordinates?:[number,number][]};legs?:{steps?:Step[]}[]};

declare global{interface Window{L?:any}}
const ACTIVE=["requested","searching_rider","assigned","accepted","pickup_started","picked_up","delivering"];
const NEXT:Record<string,string>={assigned:"accepted",accepted:"pickup_started",pickup_started:"picked_up",picked_up:"delivering",delivering:"delivered"};
const LABEL:Record<string,string>={assigned:"Go to Pickup",accepted:"Confirm Pickup",pickup_started:"Confirm Pickup",picked_up:"Start Delivery",delivering:"Complete Delivery"};
const valid=(c?:Coordinate|null):c is Coordinate=>!!c&&Number.isFinite(c.latitude)&&Number.isFinite(c.longitude);
const distance=(a:Coordinate,b:Coordinate)=>{const r=6371000,p1=a.latitude*Math.PI/180,p2=b.latitude*Math.PI/180,dp=(b.latitude-a.latitude)*Math.PI/180,dl=(b.longitude-a.longitude)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*r*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};
function useLeaflet(){const[ready,setReady]=useState(false);useEffect(()=>{if(typeof window==='undefined')return;if(window.L){setReady(true);return;}const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.async=true;s.onload=()=>setReady(true);document.body.appendChild(s);return()=>{s.remove();css.remove();};},[]);return ready;}
function instruction(step?:Step){if(!step)return'Follow the highlighted route';const t=step.maneuver?.type,m=step.maneuver?.modifier;if(t==='arrive')return'Arrive at your destination';if(t==='depart')return'Head out';if(t==='roundabout')return'Enter the roundabout';if(t==='merge')return`Merge${m?` ${m}`:''}`;if(t==='fork')return`Keep ${m??'ahead'}`;if(m)return`Turn ${m}`;return'Continue straight';}

export function RiderAppV4(){
 const[profile,setProfile]=useState<Profile|null>(null),[jobs,setJobs]=useState<Job[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[location,setLocation]=useState<Coordinate|null>(null),[heading,setHeading]=useState(0),[tab,setTab]=useState<'orders'|'map'>('orders'),[navigating,setNavigating]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const hydrate=useCallback(async()=>{const[p,j]=await Promise.all([apiFetch<Profile>('/rider/me'),apiFetch<Job[]>('/rider/jobs')]);setProfile(p);setJobs(j);setSelectedId(old=>old&&j.some(x=>x.id===old)?old:j.find(x=>ACTIVE.includes(x.status))?.id??null);},[]);
 useEffect(()=>{hydrate().catch(e=>setError(e instanceof Error?e.message:'Unable to load rider data'));},[hydrate]);
 useEffect(()=>{if(!profile||profile.status==='offline'||profile.status==='suspended'||!navigator.geolocation)return;const watch=navigator.geolocation.watchPosition(pos=>{const c={latitude:pos.coords.latitude,longitude:pos.coords.longitude};setLocation(c);if(pos.coords.heading!=null&&pos.coords.heading>=0)setHeading(pos.coords.heading);void apiFetch('/rider/location',{method:'POST',body:JSON.stringify({latitude:c.latitude,longitude:c.longitude,heading:pos.coords.heading??undefined,speed:pos.coords.speed??undefined})}).catch(()=>undefined);},()=>undefined,{enableHighAccuracy:true,maximumAge:3000,timeout:10000});return()=>navigator.geolocation.clearWatch(watch);},[profile?.status]);
 const active=useMemo(()=>jobs.filter(j=>ACTIVE.includes(j.status)),[jobs]);const delivered=useMemo(()=>jobs.filter(j=>j.status==='delivered'),[jobs]);const selected=jobs.find(j=>j.id===selectedId)??active[0]??null;
 async function toggle(){if(!profile||profile.status==='suspended')return;setBusy(true);setError(null);try{setProfile(await apiFetch<Profile>('/rider/status',{method:'PATCH',body:JSON.stringify({status:profile.status==='online'?'offline':'online'})}));}catch(e){setError(e instanceof Error?e.message:'Unable to update status');}finally{setBusy(false);}}
 async function advance(job:Job){if(!NEXT[job.status])return;setBusy(true);setError(null);try{await apiFetch(`/rider/jobs/${job.id}/status`,{method:'PATCH',body:JSON.stringify({status:NEXT[job.status]})});await hydrate();}catch(e){setError(e instanceof Error?e.message:'Unable to update order');}finally{setBusy(false);}}
 function openNav(j:Job){setSelectedId(j.id);setTab('map');setNavigating(true);}
 return <div className='min-h-[100dvh] bg-[#FFF6EC] text-[#241C18] -mx-4 -my-6 lg:-mx-8 lg:-my-8'><div className='mx-auto flex min-h-[100dvh] w-full max-w-[680px] flex-col bg-[#FFF6EC] lg:border-x lg:border-[#F0E4D6]'><header className='rounded-b-[30px] bg-[#F4581D] px-5 py-5 text-white'><div className='flex items-center justify-between'><button onClick={()=>{setTab('orders');setNavigating(false)}} className='flex h-10 w-10 items-center justify-center'><ArrowLeft size={22}/></button><div className='text-center'><div className='text-[15px] font-extrabold italic'>Empanada</div><div className='text-[17px] font-black italic text-[#3B140A]'>Hauz Rider</div></div><Bell size={21}/></div></header>{error&&<div className='mx-5 mt-3 rounded-2xl border border-[#F3D2B6] bg-[#FFF0E3] px-4 py-3 text-xs font-semibold text-[#8A3E1D]'>{error}</div>}<main className='flex-1 overflow-y-auto pb-24'>{tab==='orders'?<Orders profile={profile} jobs={active} delivered={delivered} busy={busy} onOnline={toggle} onRefresh={hydrate} onNavigate={openNav} onAdvance={advance}/>:<NavigationScreen job={selected} riderLocation={location??profile?.locations?.[0]??null} heading={heading} navigating={navigating} onBack={()=>{setTab('orders');setNavigating(false)}} onAdvance={advance} busy={busy}/>}</main><nav className='fixed bottom-0 left-1/2 z-50 flex w-full max-w-[680px] -translate-x-1/2 border-t border-[#F0E4D6] bg-white px-2 pb-2 pt-2'><button onClick={()=>setTab('orders')} className={`flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black ${tab==='orders'?'text-[#F4581D]':'text-[#8A817A]'}`}>🧾<span>Orders</span></button><button onClick={()=>setTab('map')} className={`flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black ${tab==='map'?'text-[#F4581D]':'text-[#8A817A]'}`}>🗺️<span>Map</span></button><button className='flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black text-[#8A817A]'>📊<span>Earnings</span></button><button className='flex flex-1 flex-col items-center gap-1 py-1 text-[11px] font-black text-[#8A817A]'>👤<span>Profile</span></button></nav></div></div>;
}
function Orders({profile,jobs,delivered,busy,onOnline,onRefresh,onNavigate,onAdvance}:{profile:Profile|null;jobs:Job[];delivered:Job[];busy:boolean;onOnline:()=>void;onRefresh:()=>void;onNavigate:(j:Job)=>void;onAdvance:(j:Job)=>void}){return <div className='pt-5'><div className='mx-5 rounded-full bg-white px-4 py-3 shadow-sm ring-1 ring-[#F0E4D6] flex items-center justify-between'><button disabled={busy} onClick={onOnline} className={`rounded-full px-3 py-1.5 text-xs font-black ${profile?.status==='online'?'bg-[#E4F6EB] text-[#1FA35A]':'bg-[#F6EEE7] text-[#8A817A]'}`}>{profile?.status==='online'?'● Online':'○ Offline'}</button><span className='text-[11px] font-bold text-[#8A817A]'>{jobs.length} active · {(profile?.rating??5).toFixed(1)} ⭐</span></div><div className='mt-3 flex gap-3 px-5'><Stat value={String(jobs.length)} label='Active Orders'/><Stat value={String(profile?.completedJobs??0)} label='Completed'/><Stat value={`${(profile?.rating??5).toFixed(1)} ⭐`} label='Rider Rating'/></div><Title text='Active Orders' count={jobs.length}/>{jobs.length?jobs.map(j=><OrderCard key={j.id} job={j} busy={busy} onNavigate={onNavigate} onAdvance={onAdvance}/>):<div className='mx-5 rounded-[22px] bg-white p-7 text-center ring-1 ring-[#F0E4D6]'><div className='text-3xl'>🥟</div><div className='mt-2 text-sm font-black'>{profile?.status==='online'?'Waiting for an order':"You're offline"}</div></div>}<Title text='Recent Orders'/><div className='mx-5 rounded-[22px] bg-white ring-1 ring-[#F0E4D6]'>{delivered.length?delivered.slice(0,8).map((j,i)=><div key={j.id} className={`flex items-center gap-3 px-4 py-3.5 ${i<Math.min(7,delivered.length-1)?'border-b border-[#F0E4D6]':''}`}><div className='flex h-11 w-11 items-center justify-center rounded-xl bg-[#FFE3D2] text-xl'>🥟</div><div className='min-w-0 flex-1'><div className='truncate text-[13px] font-black'>{j.order?.customer.name??'Customer'}</div><div className='truncate text-[11px] text-[#8A817A]'>{j.dropoffAddress}</div></div><div className='text-right'><div className='text-xs font-black text-[#1FA35A]'>₱{Number(j.finalFare??j.estimatedFare??0).toFixed(0)}</div><div className='text-[10px] text-[#8A817A]'>Delivered</div></div></div>):<div className='p-5 text-center text-xs text-[#8A817A]'>No deliveries completed yet.</div>}</div><button onClick={onRefresh} className='mx-5 mt-3 flex w-[calc(100%-40px)] items-center justify-center gap-2 rounded-2xl bg-white py-3 text-xs font-black ring-1 ring-[#F0E4D6]'><RefreshCw size={14}/>Refresh</button></div>}
function OrderCard({job,busy,onNavigate,onAdvance}:{job:Job;busy:boolean;onNavigate:(j:Job)=>void;onAdvance:(j:Job)=>void}){const drop=['picked_up','delivering'].includes(job.status),fare=Number(job.finalFare??job.estimatedFare??0);return <div className='mx-5 mb-3 rounded-[22px] border-[1.5px] border-[#F4581D] bg-white p-4 shadow-sm'><div className='flex items-center justify-between'><span className='rounded-[10px] bg-[#FFE3D2] px-2.5 py-1.5 text-[11px] font-extrabold text-[#D9430F]'>{job.status==='assigned'?'🕐 New Order':'🚴 Current Order'}</span><span className='text-xs font-extrabold text-[#8A817A]'>#{job.order?.orderNumber??job.id.slice(-6).toUpperCase()}</span></div><div className='mt-4 flex items-start gap-3.5'><div className='flex h-14 w-14 items-center justify-center rounded-2xl bg-[#FFE3D2] text-[26px]'>🥟</div><div className='min-w-0 flex-1'><div className='text-[15px] font-extrabold'>👤 {job.order?.customer.name??'Customer'}</div><div className='mt-1 text-[13px] leading-[18px] text-[#5C5450]'>📍 {drop?job.dropoffAddress:job.pickupAddress}</div></div></div><div className='mt-4 flex gap-2'><div className='flex-1'><div className='text-[19px] font-black'>₱{fare.toFixed(0)}</div>{job.order?.quantity&&<div className='text-[11px] text-[#8A817A]'>{job.order.quantity} pcs Empanada</div>}</div><button disabled={busy} onClick={()=>onNavigate(job)} className='rounded-2xl border border-[#F4581D] bg-white px-3 py-3 text-[12px] font-black text-[#F4581D]'><Navigation size={14} className='mr-1 inline'/>Navigate</button><button disabled={busy||!NEXT[job.status]} onClick={()=>onAdvance(job)} className='rounded-2xl bg-[#F4581D] px-3 py-3 text-[12px] font-black text-white'>{busy?'Updating…':LABEL[job.status]??'Open Order'}</button></div>{job.order?.customer.phoneNumber&&<a href={`tel:${job.order.customer.phoneNumber}`} className='mt-2 flex items-center justify-center gap-2 rounded-xl bg-[#F6EEE7] py-2 text-xs font-black text-[#5C5450]'><Phone size={13}/>Call customer</a>}</div>}
function Title({text,count}:{text:string;count?:number}){return <div className='mt-6 mb-3 flex items-center justify-between px-5'><div className='text-[15px] font-black'>{text}</div>{count!==undefined&&<div className='rounded-full bg-[#FFE3D2] px-2.5 py-1 text-[10px] font-black text-[#D9430F]'>{count}</div>}</div>}
function Stat({value,label}:{value:string;label:string}){return <div className='flex-1 rounded-[18px] bg-white p-3 text-center ring-1 ring-[#F0E4D6]'><div className='text-[17px] font-black'>{value}</div><div className='mt-0.5 text-[10px] text-[#8A817A]'>{label}</div></div>}

function NavigationScreen({job,riderLocation,heading,navigating,onBack,onAdvance,busy}:{job:Job|null;riderLocation:Coordinate|null;heading:number;navigating:boolean;onBack:()=>void;onAdvance:(j:Job)=>void;busy:boolean}){
 const leaflet=useLeaflet(),mapRef=useRef<any>(null),mapEl=useRef<HTMLDivElement|null>(null),layers=useRef<any[]>([]),lastRoute=useRef<Coordinate|null>(null);
 const[route,setRoute]=useState<Route|null>(null),[routeError,setRouteError]=useState<string|null>(null),[follow,setFollow]=useState(true);
 const destination=useMemo(()=>{if(!job)return null;const drop=['picked_up','delivering'].includes(job.status);const lat=Number(drop?job.dropoffLatitude:job.pickupLatitude),lng=Number(drop?job.dropoffLongitude:job.pickupLongitude);return Number.isFinite(lat)&&Number.isFinite(lng)?{latitude:lat,longitude:lng}:null;},[job]);
 useEffect(()=>{if(!leaflet||!mapEl.current||mapRef.current)return;const L=window.L;if(!L)return;const m=L.map(mapEl.current,{zoomControl:false,attributionControl:true}).setView([10.3157,123.8854],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(m);mapRef.current=m;setTimeout(()=>m.invalidateSize(),100);return()=>{m.remove();mapRef.current=null;};},[leaflet]);
 useEffect(()=>{if(!riderLocation||!destination)return;const moved=!lastRoute.current||distance(lastRoute.current,riderLocation)>80;if(!moved&&route)return;lastRoute.current=riderLocation;let cancelled=false;setRouteError(null);const u=`https://router.project-osrm.org/route/v1/driving/${riderLocation.longitude},${riderLocation.latitude};${destination.longitude},${destination.latitude}?overview=full&geometries=geojson&steps=true`;fetch(u).then(async r=>{if(!r.ok)throw new Error('Routing service unavailable');const d=await r.json();const candidate=d?.routes?.[0];if(!candidate?.geometry?.coordinates?.length)throw new Error('No driving route found');return candidate as Route;}).then(r=>{if(!cancelled)setRoute(r);}).catch(e=>{if(!cancelled)setRouteError(e instanceof Error?e.message:'Unable to calculate route');});return()=>{cancelled=true;};},[riderLocation,destination,route]);
 useEffect(()=>{const map=mapRef.current,L=window.L;if(!map||!L)return;layers.current.forEach(x=>{try{map.removeLayer(x)}catch{}});layers.current=[];if(riderLocation){const icon=L.divIcon({className:'rider-arrow',html:`<div style="transform:rotate(${heading}deg);font-size:34px;line-height:34px;filter:drop-shadow(0 2px 3px rgba(0,0,0,.35))">🏍️</div>`,iconSize:[40,40],iconAnchor:[20,20]});layers.current.push(L.marker([riderLocation.latitude,riderLocation.longitude],{icon}).addTo(map));}if(destination){const icon=L.divIcon({className:'destination',html:'<div style="width:34px;height:34px;border-radius:50%;background:#241C18;border:3px solid white;display:grid;place-items:center;color:white;font-size:17px">📍</div>',iconSize:[34,34],iconAnchor:[17,17]});layers.current.push(L.marker([destination.latitude,destination.longitude],{icon}).addTo(map));}const coords=route?.geometry?.coordinates;if(Array.isArray(coords)&&coords.length>1){const points=coords.map(([lng,lat])=>[lat,lng]);layers.current.push(L.polyline(points,{color:'#F4581D',weight:8,opacity:.9,lineCap:'round',lineJoin:'round'}).addTo(map));if(follow)map.fitBounds(L.latLngBounds(points),{padding:[70,70],maxZoom:17});}else if(riderLocation&&follow)map.setView([riderLocation.latitude,riderLocation.longitude],17);},[riderLocation,destination,route,heading,follow]);
 const steps=route?.legs?.[0]?.steps??[],next=steps.find(s=>(s.distance??0)>20)??steps[0],minutes=route?Math.max(1,Math.round(route.duration/60)):job?.estimatedDurationMinutes??null,km=route?route.distance/1000:job?.distanceKm??null,drop=job&&['picked_up','delivering'].includes(job.status);
 return <div className={navigating?'fixed inset-0 z-[100] bg-[#111]':'pt-3'}><div ref={mapEl} className={navigating?'absolute inset-0':'mx-5 h-[min(62vh,600px)] overflow-hidden rounded-[22px] bg-slate-200 shadow-sm'}/>{job&&<><div className='absolute left-4 right-4 top-4 z-[500] rounded-2xl bg-white/95 p-4 shadow-xl backdrop-blur'><div className='flex items-center gap-3'><Navigation className='text-[#F4581D]' size={22}/><div className='min-w-0 flex-1'><div className='text-[10px] font-black uppercase tracking-wider text-[#8A817A]'>{drop?'Delivering to':'Heading to pickup'}</div><div className='truncate text-sm font-black'>{drop?job.dropoffAddress:job.pickupAddress}</div></div><button onClick={onBack} className='rounded-xl bg-[#F6EEE7] px-3 py-2 text-xs font-black'>Close</button></div></div>{navigating&&<div className='absolute bottom-4 left-4 right-4 z-[500] rounded-[24px] bg-white p-4 shadow-2xl'><div className='text-[18px] font-black'>{instruction(next)}</div><div className='mt-2 flex gap-3 text-xs font-bold text-[#5C5450]'><span>{km!=null?`${km.toFixed(1)} km`:'Calculating…'}</span><span>·</span><span>{minutes!=null?`${minutes} min`:'Route'}</span></div>{routeError&&<div className='mt-2 text-xs font-semibold text-[#A43D1D]'>{routeError}</div>}<div className='mt-3 flex gap-2'><button onClick={()=>{setFollow(true);if(riderLocation)mapRef.current?.setView([riderLocation.latitude,riderLocation.longitude],17)}} className='flex flex-1 items-center justify-center gap-2 rounded-2xl bg-[#F6EEE7] py-3 text-xs font-black'><LocateFixed size={15}/>Recenter</button><button disabled={busy||!NEXT[job.status]} onClick={()=>onAdvance(job)} className='flex-[1.5] rounded-2xl bg-[#F4581D] py-3 text-xs font-black text-white'>{busy?'Updating…':LABEL[job.status]}</button></div><button onClick={()=>setFollow(v=>!v)} className='mt-2 w-full text-center text-[11px] font-black text-[#8A817A]'>{follow?'Auto-follow ON · tap to unlock':'Auto-follow OFF · tap to follow'}</button></div>}</>}{!navigating&&<div className='mx-5 mt-3 rounded-[22px] bg-white p-4 ring-1 ring-[#F0E4D6]'><div className='text-sm font-black'>{job.order?.customer.name??'Customer'}</div><div className='mt-1 text-xs text-[#8A817A]'>{km!=null?`${km.toFixed(1)} km`:'Route'} · {minutes!=null?`${minutes} min`:''}</div><button onClick={()=>setFollow(true)} className='mt-3 w-full rounded-2xl bg-[#F4581D] py-3 text-xs font-black text-white'>Start navigation</button></div>}</div>;
}