import { useEffect, useMemo, useRef, useState } from "react";
import MapView, { Marker, Polyline, Region } from "react-native-maps";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";

const DIRECTIONS_API_KEY = process.env.EXPO_PUBLIC_GOOGLE_DIRECTIONS_API_KEY ?? process.env.EXPO_PUBLIC_GOOGLE_MAPS_API_KEY;
type Coordinate = { latitude: number; longitude: number };
type Props = { riderLocation?: Coordinate | null; pickup?: Coordinate | null; dropoff?: Coordinate | null; pickupAddress?: string; dropoffAddress?: string; onClose?: () => void };
const valid = (p?: Coordinate | null): p is Coordinate => !!p && Number.isFinite(p.latitude) && Number.isFinite(p.longitude);
function region(points: Coordinate[]): Region { const p=points.filter(valid); if(!p.length)return {latitude:10.3157,longitude:123.8854,latitudeDelta:.08,longitudeDelta:.08}; const minLat=Math.min(...p.map(x=>x.latitude)),maxLat=Math.max(...p.map(x=>x.latitude)),minLng=Math.min(...p.map(x=>x.longitude)),maxLng=Math.max(...p.map(x=>x.longitude)); return {latitude:(minLat+maxLat)/2,longitude:(minLng+maxLng)/2,latitudeDelta:Math.max(.012,(maxLat-minLat)*1.5),longitudeDelta:Math.max(.012,(maxLng-minLng)*1.5)}; }
function decode(s:string){let i=0,lat=0,lng=0;const out:Coordinate[]=[];while(i<s.length){let b=0,r=0,shift=0;do{b=s.charCodeAt(i++)-63;r|=(b&31)<<shift;shift+=5}while(b>=32);lat+=r&1?~(r>>1):r>>1;r=0;shift=0;do{b=s.charCodeAt(i++)-63;r|=(b&31)<<shift;shift+=5}while(b>=32);lng+=r&1?~(r>>1):r>>1;out.push({latitude:lat/1e5,longitude:lng/1e5})}return out}
async function route(origin:Coordinate,destination:Coordinate,waypoint?:Coordinate|null){if(!DIRECTIONS_API_KEY)return null;const q=new URLSearchParams({origin:`${origin.latitude},${origin.longitude}`,destination:`${destination.latitude},${destination.longitude}`,key:DIRECTIONS_API_KEY,mode:"driving"});if(valid(waypoint))q.set("waypoints",`${waypoint.latitude},${waypoint.longitude}`);const r=await fetch(`https://maps.googleapis.com/maps/api/directions/json?${q}`);const d=await r.json();if(!r.ok||d.status!=="OK"||!d.routes?.[0])throw Error(d.error_message||d.status||"Unable to calculate route");const legs=d.routes[0].legs??[];return {points:decode(d.routes[0].overview_polyline?.points??""),distance:legs.reduce((n:any,x:any)=>n+(x.distance?.value??0),0)/1000,duration:legs.map((x:any)=>x.duration?.text).filter(Boolean).join(" + ")}}
export default function RiderMapView({riderLocation,pickup,dropoff,pickupAddress,dropoffAddress,onClose}:Props){const map=useRef<MapView>(null);const [path,setPath]=useState<Coordinate[]>([]),[info,setInfo]=useState<{distance:number;duration:string}|null>(null),[loading,setLoading]=useState(false),[following,setFollowing]=useState(false),[routeError,setRouteError]=useState<string|null>(null);const points=useMemo(()=>[riderLocation,pickup,dropoff].filter(valid),[riderLocation,pickup,dropoff]);const target=dropoff??pickup??null;
useEffect(()=>{if(points.length)requestAnimationFrame(()=>map.current?.fitToCoordinates(points,{edgePadding:{top:170,right:60,bottom:300,left:60},animated:true}))},[pickup?.latitude,pickup?.longitude,dropoff?.latitude,dropoff?.longitude]);
useEffect(()=>{const origin=riderLocation??pickup??null;if(!valid(origin)||!valid(target)){setPath([]);setInfo(null);return}if(!DIRECTIONS_API_KEY){setPath([origin,target]);setRouteError("Route preview is shown. Configure EXPO_PUBLIC_GOOGLE_DIRECTIONS_API_KEY or EXPO_PUBLIC_GOOGLE_MAPS_API_KEY for turn-by-turn routing.");return}let dead=false;setLoading(true);setRouteError(null);route(origin,target,pickup&&target!==pickup?pickup:null).then(x=>{if(!dead&&x){setPath(x.points.length>1?x.points:[origin,target]);setInfo({distance:x.distance,duration:x.duration})}}).catch(e=>{if(!dead){setPath([origin,target]);setRouteError(e instanceof Error?e.message:"Unable to calculate route")}}).finally(()=>!dead&&setLoading(false));return()=>{dead=true}},[riderLocation?.latitude,riderLocation?.longitude,pickup?.latitude,pickup?.longitude,dropoff?.latitude,dropoff?.longitude]);
useEffect(()=>{if(following&&valid(riderLocation))map.current?.animateToRegion({latitude:riderLocation.latitude,longitude:riderLocation.longitude,latitudeDelta:.012,longitudeDelta:.012},450)},[following,riderLocation?.latitude,riderLocation?.longitude]);
return <View style={s.container}><MapView ref={map} style={StyleSheet.absoluteFill} initialRegion={region(points)} showsUserLocation={valid(riderLocation)} showsMyLocationButton={false} onPanDrag={()=>setFollowing(false)}>{valid(riderLocation)?<Marker coordinate={riderLocation} title="You"><View style={s.riderDot}/></Marker>:null}{valid(pickup)?<Marker coordinate={pickup} title="Pickup" description={pickupAddress}><View style={s.pick}><Text style={s.markerText}>▣</Text></View></Marker>:null}{valid(dropoff)?<Marker coordinate={dropoff} title="Drop-off" description={dropoffAddress}><View style={s.drop}><Text style={s.markerText}>⌂</Text></View></Marker>:null}{path.length>1?<Polyline coordinates={path} strokeColor="#ff4a14" strokeWidth={5} lineDashPattern={info?undefined:[10,8]}/>:null}</MapView>
<View style={s.header}><View style={s.menu}><Text style={s.menuText}>☰</Text></View><View style={s.brand}><Text style={s.brandTop}>Empanada</Text><Text style={s.brandBottom}>Hauz</Text></View><View style={s.online}><View style={s.green}/><Text style={s.onlineText}>Online</Text></View></View>
<View style={s.side}>{!following&&valid(riderLocation)?<Pressable style={s.round} onPress={()=>setFollowing(true)}><Text style={s.roundText}>⌖</Text></Pressable>:null}<Pressable style={s.round} onPress={()=>map.current?.fitToCoordinates(points,{edgePadding:{top:170,right:50,bottom:280,left:50},animated:true})}><Text style={s.roundText}>◎</Text></Pressable></View>
<View style={s.current}><View style={s.orderNum}><Text style={s.orderNumText}>1</Text></View><View style={{flex:1}}><View style={s.row}><Text style={s.currentTitle}>Current Order</Text><View style={s.pickPill}><Text style={s.pickPillText}>{valid(pickup)?"Pickup":"Delivery"}</Text></View></View><Text style={s.address} numberOfLines={1}>{pickupAddress??dropoffAddress??"Location pending"}</Text><Text style={s.sub}>{loading?"Calculating route…":info?`${info.distance.toFixed(1)} km • ${info.duration}`:routeError??"Pickup → Drop-off"}</Text></View></View>
{routeError&&!DIRECTIONS_API_KEY?<View style={s.notice}><Text style={s.noticeText}>Route preview mode</Text></View>:null}{onClose?<Pressable onPress={onClose} style={s.close}><Text style={s.closeText}>×</Text></Pressable>:null}</View>}
const s=StyleSheet.create({container:{flex:1,backgroundColor:"#ece7dc"},header:{position:"absolute",top:0,left:0,right:0,height:104,backgroundColor:"#ff5a12",borderBottomLeftRadius:32,borderBottomRightRadius:32,flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:22,paddingTop:24,elevation:8},menu:{width:42},menuText:{fontSize:30,color:"#fff",fontWeight:"500"},brand:{alignItems:"center"},brandTop:{fontSize:19,fontWeight:"900",fontStyle:"italic",color:"#35160c",lineHeight:20},brandBottom:{fontSize:23,fontWeight:"900",fontStyle:"italic",color:"#fff",lineHeight:22},online:{backgroundColor:"#fff",borderRadius:20,paddingHorizontal:12,paddingVertical:8,flexDirection:"row",alignItems:"center",gap:7},green:{width:10,height:10,borderRadius:5,backgroundColor:"#16a34a"},onlineText:{fontWeight:"800",color:"#252525",fontSize:13},side:{position:"absolute",right:20,top:220,gap:14},round:{width:58,height:58,borderRadius:29,backgroundColor:"#fff",alignItems:"center",justifyContent:"center",elevation:5},roundText:{fontSize:28,color:"#ff4a14",fontWeight:"800"},current:{position:"absolute",top:128,left:18,right:18,backgroundColor:"rgba(255,255,255,.97)",borderRadius:22,padding:16,flexDirection:"row",gap:12,elevation:6},orderNum:{width:42,height:42,borderRadius:14,backgroundColor:"#ff4a14",alignItems:"center",justifyContent:"center"},orderNumText:{color:"#fff",fontSize:21,fontWeight:"900"},row:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:8},currentTitle:{color:"#df4618",fontSize:17,fontWeight:"900"},pickPill:{backgroundColor:"#262626",borderRadius:16,paddingHorizontal:10,paddingVertical:5},pickPillText:{color:"#fff",fontWeight:"800",fontSize:11},address:{color:"#252525",fontSize:15,fontWeight:"800",marginTop:4},sub:{color:"#777",fontSize:12,marginTop:4},riderDot:{width:24,height:24,borderRadius:12,backgroundColor:"#ff4a14",borderWidth:5,borderColor:"#fff"},pick:{width:50,height:50,borderRadius:25,backgroundColor:"#ff5a12",borderWidth:3,borderColor:"#fff",alignItems:"center",justifyContent:"center"},drop:{width:50,height:50,borderRadius:25,backgroundColor:"#ef3f23",borderWidth:3,borderColor:"#fff",alignItems:"center",justifyContent:"center"},markerText:{color:"#fff",fontSize:22,fontWeight:"900"},notice:{position:"absolute",left:20,bottom:26,backgroundColor:"rgba(255,255,255,.92)",borderRadius:14,paddingHorizontal:12,paddingVertical:8},noticeText:{color:"#8b5b3e",fontSize:11,fontWeight:"800"},close:{position:"absolute",right:18,bottom:32,width:46,height:46,borderRadius:23,backgroundColor:"#fff",alignItems:"center",justifyContent:"center",elevation:5},closeText:{fontSize:30,color:"#ff4a14",lineHeight:34}});